### ISSUE TITLE
is there any way using this gem with rails engines

### ISSUE THREAD

**Issue by farukca** [glebm/i18n-tasks#105]
Let's say we have a main_app and auther rails engine. The folder structure is something like;
main_app/app ...
auther/app ..

So, some locale files are under auther/config/locales. And some of them are located under main_app/config/locales.

Now, in i18n-tasks.yml file I have add the files;
data:
  read:
    - config/locales/_.%{locale}.yml
    - ../auther/config/locales/_.%{locale}.yml

But it is saying;
i18n-tasks: Adapter not found for ../auther/config/locales/simple_form.en.yml. Registered adapters: [[:yaml, "_.yml", I18n::Tasks::Data::Adapter::YamlAdapter], [:json, "_.json", I18n::Tasks::Data::Adapter::JsonAdapter]]

How can we solve this issue ?

Best regards.

**Comment by Marnes** [comment]
I'm getting the same issue when I use

```
data:
  read:
    - 'config/locales/*.%{locale}.yml'
    - '../engine/config/locales/*.%{locale}.yml'
```

but when I use the full path it works fine e.g.

```
data:
  read:
    - 'config/locales/*.%{locale}.yml'
    - '/home/full/path/engine/config/locales/*.%{locale}.yml'
```

**Comment by Arsen7** [comment]
I'm not sure you guys are still interested in this, but the problem is in how `File.fnmatch` treats paths starting with a dot:
```
File.fnmatch  '*.yml', '../engine/config/locales/en.yml' # => false
File.fnmatch  '*.yml',    'engine/config/locales/en.yml' # => true
File.fnmatch '.*.yml', '../engine/config/locales/en.yml' # => true
````

So, any path starting with a dot is considered "hidden" (wrongly).

@glebm : What would you think about this change?
```
diff --git a/lib/i18n/tasks/data/file_formats.rb b/lib/i18n/tasks/data/file_formats.rb
index e5a0959..964bf48 100644
--- a/lib/i18n/tasks/data/file_formats.rb
+++ b/lib/i18n/tasks/data/file_formats.rb
@@ -69,7 +69,7 @@ module I18n
 
           def adapter_name_for_path(path)
             @fn_patterns.detect do |(_name, pattern, _adapter)|
-              ::File.fnmatch(pattern, path)
+              ::File.fnmatch(pattern, ::File.basename(path))
             end.try(:first) || fail(
               CommandError, "Adapter not found for #{path}. Registered adapters: #{@fn_patterns.inspect}"
             )
```

**Comment by glebm** [comment]
@Arsen7 Thanks for figuring out what the problem is.

> @glebm : What would you think about this change?

That seems OK but is that change enough? If yes, I wouldn't oppose merging it, though perhaps using `**/*.yml` pattern and `File.expand_path(path)` is better as it's more flexible.

In any case, rather than relying on a particular directory structure, it is more robust to do e.g. `<%= %x[bundle show engine].chomp %>/config/locales/*.%{locale}.yml %>`.
