### ISSUE TITLE
Relative key not reported as missing when helper method not used

### ISSUE THREAD

**Issue by jawa** [glebm/i18n-tasks#106]
Hi, not really sure whether this qualifies as an issue or not, but I thought it would be good to let you know about it.

In my view I had mistakenly written `I18n.t('.some_key')` which i18n-tasks considered used since there was a corresponding key `path.to.view.some_key` in my translation files. However, it seems like relative keys only works when used with the `translate`/`t` helper so when I viewed the page, the translation was missing even though i18n-tasks had reported no missing translations.

Thanks for a very useful tool in managing translations otherwise!
/Jakob

**Comment by glebm** [comment]
This is now available in v0.9.0.rc2 (only for .rb files), and will be available in v0.9.0 release.
