### ISSUE TITLE
remove-unused not working, composed task does

### ISSUE THREAD

**Issue by allaire** [glebm/i18n-tasks#108]
Hi,

`remove unused` is not working in my case, but `i18n-tasks unused -fyaml | i18n-tasks data-remove` does.

My case is quite special, in my i18n-tasks config I have `config/locales/**/*.yml` for both `read` and `write`. What's special is that I have a directory under `locales/` that is called `_sources/`. This folder contains duplicate data for the `fr` language (we're using crowdin.net and it's a neat trick that I found).

`remove unused` delete every keys/strings I have in `_sources/`, where the other composed task option works correctly and remove duplication like `i18n-tasks unused` shows.

Any ideas?

Thanks!

**Comment by glebm** [comment]
This might be fixed in v0.8.6, please give it a try.
