### ISSUE TITLE
Guidance on custom key matching

### ISSUE THREAD

**Issue by philostler** [glebm/i18n-tasks#110]
I'm mainly looking for guidance, but you could argue that this is an issue in itself (I can't work out how to do this from the docs).

I dynamically build keys for I18n strings in my app in the following form...
```ruby
serialize_error(%i(path to key)
```
This then resolves to two keys...
```ruby
I18n.t "path.to.key.code"
I18n.t "path.to.key.message"
```

Where would I even begin to start making this work so I can check on unused keys etc? I'm guessing a custom scanner...??

Thanks

**Comment by glebm** [comment]
This will be a lot easier with v0.9. Please see the example here: https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example.
