### ISSUE TITLE
Scanner will skip valid translation and say it is unused

### ISSUE THREAD

**Issue by kieranklaassen** [glebm/i18n-tasks#111]
I have a haml file, that renders a div with id success with this line:

``` haml
#success= t('translation')
```

## Expect:

The i18n-tasks health should pass

## Actual:

i18n-tasks thinks it is unused. Probably it sees it as an ruby comment so skipping.

This works but the other syntax should work.

``` haml
%div#success= t('translation')
```

**Comment by glebm** [comment]
Fixed in 0.5.2 (a while ago).
