### ISSUE TITLE
i18n-tasks unused greps comments for translation keys, too

### ISSUE THREAD

**Issue by jakeonrails** [glebm/i18n-tasks#112]
I'd expect it to ignore comments.

I had a comment with the text `t(".title")` and it raised an error with i18n-tasks because that key did not exist.

**Comment by glebm** [comment]
Comments are ignored since v0.5.2. https://github.com/glebm/i18n-tasks/blob/f6ad75b0d86dc5d2f899516349106f8b01efffca/lib/i18n/tasks/scanners/base_scanner.rb#L29-L35 Dupe: #73

**Comment by jakeonrails** [comment]
Thanks, did not realize we weren't using the latest version. I'll upgrade us!
