### ISSUE TITLE
private method `load' called for Psych:Module 

### ISSUE THREAD

**Issue by geoffharcourt** [glebm/i18n-tasks#114]
```shell
[master] ✔ i18n-tasks
/Users/geoff/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.7.9/lib/i18n/tasks/configuration.rb:16:in `file_config': private method `load' called for Psych:Module (NoMethodError)
```

This issue seems to be similar to the reports on this cocoapods issue: https://github.com/CocoaPods/CocoaPods/issues/2908

Something about psych 2.0.8 causes a public/private problem when `Psych.load` is called that raises an exception.

**Comment by geoffharcourt** [comment]
Psych 2.0.8 is the default with Ruby 2.2.0, so there's currently no way to get around this in Ruby 2.2.

**Comment by glebm** [comment]
I am waiting for the company I work for to approve my further contributions to this project, I'll fix this as soon as I get one.

**Comment by geoffharcourt** [comment]
@glebm, is this a situation where if someone else wrote the PR that you could merge it without waiting for approval? I'm happy to take a crack at the PR if that would help.

**Comment by glebm** [comment]
@geoffharcourt I can commit and merge stuff now :) I cannot reproduce the problem using Ruby 2.2, also from you stack trace looks like .rbenv is using 2.1.5?

**Comment by geoffharcourt** [comment]
@glebm, what version of psych do you have installed?

**Comment by andela-bolanrewaju** [comment]
I was faced with the same error on ruby version 2.2.3. All I did was run with `bundle exec` prepended to `i18n-tasks missing`

**Comment by Sonblind** [comment]
:+1: `bundle exec` did the trick for me too
