### ISSUE TITLE
missing keys reported incorrectly

### ISSUE THREAD

**Issue by dancinglightning** [glebm/i18n-tasks#117]
Well, first off: great project.

In my app, i use translation keys that are defined in a gem (engine)
They get reported as missing, even they are not.
Off course i can work around that with the config, but i still feel it's a bug. In the sense that is reported missing but using the key will create  a valid translation.

I would be happy to help with this, given a few pointers.

On another note: I have some code that did something quite similar though a web-api. 
That was also very useful as we had domain experts translating.
Would you be interested in such a ui, i could port it to your (probably much better) base code.

**Comment by glebm** [comment]
You can [load the keys from a gem](https://github.com/glebm/i18n-tasks#multiple-locale-files) using the config! A web UI would be fantastic but it can live in a separate gem and use i18n-tasks.

**Comment by glebm** [comment]
At the moment i18n-tasks only performs static analysis, i.e. it just scans the source code without evaluating it. An improvement to this would be to have a runtime scanner that runs the specs and collects results. I've started a new job last month that doesn't involve Ruby, so I am not actively contributing to this project, but I am here to provide guidance if anyone wants to do this. Issue #81 describes what I would do if I had time to work on this.

**Comment by dancinglightning** [comment]
That is a good direction, for sure.

But much much more than what i was talking about. I just meant to do I18n.translate(key) in the rails environment (all locales loaded, also gems) and see if it returns "translation missing".

That i could manage i think, the #81 is too much for me too.

I just have all keys listed as used in the config at the moment (about 30-50) which seems a little silly.

**Comment by glebm** [comment]
Instead of listing the keys, this is a bit better:

```yaml
data:
  read:
    - "<%= %x[bundle show vagrant].chomp %>/templates/locales/%{locale}.yml"
```
