### ISSUE TITLE
report duplicate

### ISSUE THREAD

**Issue by dancinglightning** [glebm/i18n-tasks#119]
When using the nice feature of add-missing, some keys may end up untranslated. 
Especially so when using normalized files (which are great off course)

So the suggestion would be to have a command (and especially spec task) that finds duplicates in two locales.

I could do this if you sort of pre-approve it and possibly give any directions as to how it should be done.

Torsten

**Comment by glebm** [comment]
See the [`eq-base`](https://github.com/glebm/i18n-tasks/blob/master/lib/i18n/tasks/command/commands/eq_base.rb) task that shows all the keys with values equal to the one in the base locale.

**Comment by glebm** [comment]
A lot of languages have the same words for certain things, e.g. Italian and Spanish, which is why this is not in the base spec. Docs could be improved, yes.

**Comment by dancinglightning** [comment]
fair enough, didn't think of that (only speak 3)

how about i figure out how to write a spec which does eq_base and put that into the template 
as a commented out option.
Possibly with configurable exceptions (code or config?)
