### ISSUE TITLE
Normalizing removes value quotation

### ISSUE THREAD

**Issue by oskarkrawczyk** [glebm/i18n-tasks#123]
By design all my translations values are wrapped in quotation marks, unfortunately normalizing removes quotation for some values, is there a way that this is not happening and always leaves the quotation in place?

**Comment by glebm** [comment]
All YAML parsing is delegated to `YAML`, which is [Psych](https://github.com/tenderlove/psych) by default in MRI. Unfortunately, I don't think it supports an option that does this.
