### ISSUE TITLE
Javascript and Detecting text

### ISSUE THREAD

**Issue by nroose** [glebm/i18n-tasks#124]
We are using the I18n.js package in our project, and I was wondering if you had any plans or ideas to include searching the javascript for keys.

Also, We may have only converted a small part of our project to support multiple languages, but we may do the rest.  It would be great to have a tool that finds strings and assists in converting them.  Is that on your radar?

I guess I will be trying to add these as custom tasks if you are not planning on them.  Perhaps that could eventually be a contribution to the project.

**Comment by glebm** [comment]
The scanner as it is just runs lots of regular expressions. Javascript will have very similar code in this regard, so it should work in most cases. Just add your Javascript directory to `data.read` in the config.

There are a few existing projects that extract i18n keys from the views, e.g.:

* [Slimkeyfy](https://github.com/phrase/slimkeyfy) extracts plain Strings from .slim views and Rails controllers.
* [haml-i18n-extractor](https://github.com/shaiguitar/haml-i18n-extractor) automates string extraction from haml.

It would be best to have this outside the core as plugins (separate gems). There is an example of a custom task here (https://github.com/glebm/i18n-tasks/wiki/Custom-CSV-import-and-export-tasks).

Related: #72

**Comment by nroose** [comment]
Oh, thanks!  I think you mean that the js directory should be included in search.paths.  And I guess it was finding the js already.  But I think it does not find patterns like "I18n.l('time.formats.time', new Date())".  Also, when looking at Slimkeyfy, I found the i18r gem (https://github.com/balinterdi/i15r)!

**Comment by stevenharman** [comment]
> I think it does not find patterns like "I18n.l('time.formats.time', new Date())".

This is the only mention I can find of detecting I18n localization. Specifically, it seems `i18n-tasks` does not look for/consider calls to `I18n::l` nor `I18n::localize` when looking for missing/unused keys. Can you confirm/deny that? I'm happy to open an issue to add it, or at least a PR to mention it in the `README`.

**Comment by glebm** [comment]
@stevenharman That's right, i18n-tasks does not look for `I18n.l`.
