### ISSUE TITLE
I want i18n-tasks to ensure a '.title' whenever I use a `headline_with_flash` in a view

### ISSUE THREAD

**Issue by jmuheim** [glebm/i18n-tasks#138]
I'm using a method called `headline_with_flash` in most of my views:

    h1 = headline_with_flash

The method looks like this:

```ruby
  def headline_with_flash(options = {})
    t '.title', options
  end
```

The method lives in `page_title_and_headline_helper.rb` and I had to exclude this file using

```
search:
  exclude:
    - ...
    - '*/page_title_and_headline_helper.rb'
```

Otherwise, i18n-tasks would fail:

    app/helpers/page_title_and_headline_helper.rb: cannot resolve relative key

So now I'd like i18n-tasks to make sure that whenever it meets a call to `headline_with_flash` in a view, it checks whether a corresponding `.title` key exists in the translations.

Is this possible?

**Comment by glebm** [comment]
You can extend the scanner, or work around with a magic comment:

```slim
/ i18n-tasks-use t('.title')
= headline_with_flash
```

**Comment by jmuheim** [comment]
Extending the scanner sounds promising, but it looks very complicated. Could you point me into the right direction, please?

**Comment by glebm** [comment]
You could try something like below (untested code):

In `lib/my_i18n_scanner.rb':
```ruby
class MyI18nScanner < I18n::Tasks::PatternScanner

def scan_file(path, opts = {})
  keys = super
  if path =~ /\.(slim|haml)$/
    text = opts[:text] || read_file(path)
    text.scan(/^\s*=\s*headline_with_flash\b/) do |pattern|
      location = src_location(path, text, Regexp.last_match.offset(0).first)
      keys << [absolute_key('.title', path, location), data: location]
    end
  end
  keys
end
```

In `config/i18n-tasks.yml`:

```
<% require '../lib/my_i18n_scanner' %>
search:
  scanner: MyI18nScanner
```

**Comment by glebm** [comment]
If this works out for you, please add a wiki article :+1:

**Comment by jmuheim** [comment]
I didn't have the time to really check it out. It's on my TODO list though. Thanks!

**Comment by glebm** [comment]
This is now very easy with the `0.9-dev` branch that supports multiple scanners: https://github.com/glebm/i18n-tasks/blob/0.9-dev/spec/fixtures/lib/my_custom_scanner.rb and https://github.com/glebm/i18n-tasks/blob/0.9-dev/spec/fixtures/config/i18n-tasks.yml.erb
