### ISSUE TITLE
Removing keys from slave locales based on missing keys in base

### ISSUE THREAD

**Issue by oskarkrawczyk** [glebm/i18n-tasks#140]
More of a question than issue.

Is there a way to remove keys from slave locales based on missing keys in the base locale?

For example my base EN:

```
en:
  foo: "foo"
```

Slave:

```
fr:
  foo: "foo"
  bar: "bar"
```

Running `i18n-tasks missing` will report that `bar` is missing in `en`. I don't want this, I know my base locale is correct, and all other should respect missing keys and remove them from slaves.

**Comment by glebm** [comment]
Something like below should do it:

```console
i18n-tasks missing -tdiff -len -fyaml | \
  i18n-tasks tree-rename-key en fr | \
  i18n-tasks data-remove -fyaml
```

Except I just tried it, and `data-remove` does not seem to work (although it reports that it did).

**Comment by glebm** [comment]
The command above should be working in v0.8.6, please give it a try!

**Comment by feliperaul** [comment]
@glebm since tree-rename-key doesn't exist anymore, how one would perform this task with the most recent version? It's not obvious to me 😬
