### ISSUE TITLE
Interactive patching translation files

### ISSUE THREAD

**Issue by suruja** [glebm/i18n-tasks#144]
Hello!

First of all, great work! This gem is very useful!

It would be awesome if we could interactively fix translation problems (missing keys, unused keys, ...), one problem at a time, like `git add -p` command.

Maybe I missed something and this is already possible using the interactive console?

**Comment by glebm** [comment]
Hi, this is not currently possible. This would be a really useful feature. It can be implemented as a [custom tasks](https://github.com/glebm/i18n-tasks#add-new-tasks), and if somebody manages to accomplish this then I would merge it into the gem.
