### ISSUE TITLE
Add missing attributes for Active Record

### ISSUE THREAD

**Issue by maurymmarques** [glebm/i18n-tasks#145]
Is there a way to add missing keys of attributes like this gem?
https://github.com/amatsuda/i18n_generators#2-generate-translation-yaml-file-for-all-modelsattributes
If not, do you think that it will be possible soon?
Thank you very much for your gem.

**Comment by glebm** [comment]
@maurymmarques Hi, with custom scanners released in v0.9.0 it should be trivial to add this (e.g. by calling amatsuda's gem for the actual analysis). If anyone gets a custom scanner working for this, feel free to add it to the wiki or release it as a gem. An example custom scanner can be found [here](https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example).
