### ISSUE TITLE
Workaround for use with rails 2.3.18-lts / ruby 1.9.3

### ISSUE THREAD

**Issue by ianheggie** [glebm/i18n-tasks#149]
I was unable to get quickly this working with rails 2.3.18-lts and ruby 1.9.3 due to complaints about missing activesupport classes and files. I have created a workaround for those that are interested under https://github.com/ianheggie/i18n-tasks-util (runs the i18n-utils command from the separate project in the project spec file via Bundler.with_clean_env).

I am unsure if you will want to put time into a fix for that old a rails version, or just note this work around.

**Comment by glebm** [comment]
Hi, ActiveSupport 2 support turned out to be relatively straightforward, commited as https://github.com/glebm/i18n-tasks/commit/3f963c505bb386c64f24d90503cbbc009207a5cb
