### ISSUE TITLE
Exit code of i18n-tasks CLI should be nonzero for health/missing/unused when unclean

### ISSUE THREAD

**Issue by lowjoel** [glebm/i18n-tasks#151]
Currently the CLI always returns 0. This does not allow us to run i18n-tasks as a script separately from tests and checking that there are no missing/unused translations.

An error code which represents the absence/presence of warnings would be nice.

**Comment by glebm** [comment]
SGTM.

**Comment by lowjoel** [comment]
Awesome, thanks @glebm :)
