### ISSUE TITLE
Column formatting is thrown off by CJK characters

### ISSUE THREAD

**Issue by L2G** [glebm/i18n-tasks#152]
When generating columnar reports that include messages with Chinese, Japanese, or Korean characters, the column formatting gets thrown off because CJK "full-width" characters occupy twice the space of other characters.

Using the [unicode-display_width gem](https://github.com/janlelis/unicode-display_width) is one possible way to handle this. (I imagine it being used as a "soft" dependency, since not everyone has to deal with CJK characters.)

**Comment by glebm** [comment]
Thank you for reporting this, I would accept a CL that adds this as a soft dependency. However, perhaps this should be fixed in https://github.com/tj/terminal-table, the gem i18n-tasks uses to output its tables.

**Comment by glebm** [comment]
It appears there is an outstanding CL to terminal-table fixing this: https://github.com/tj/terminal-table/pull/50

**Comment by prusswan** [comment]
feel like tagging this with `monospace` :o

**Comment by glebm** [comment]
Looks like this has been [fixed](https://github.com/tj/terminal-table/commit/871c21313861134dfc2f1e41c21d44719acbaa1a) in terminal-table 1.7.0! :tada:
