### ISSUE TITLE
i18n-tasks reads configuration too late for custom commands

### ISSUE THREAD

**Issue by halostatue** [glebm/i18n-tasks#153]
The wiki has a page for [CSV import/export tasks](https://github.com/glebm/i18n-tasks/wiki/Custom-CSV-import-and-export-tasks) that does not work with 0.8.3 because running `i18n-tasks` does not load the configuration (`config/i18n-tasks.yml.erb`) early enough to register the custom commands. Only *after* a command has been specified is the configuration loaded.

It feels like a proper plug-in system (like the simple ones that Minitest or Hoe implement) would be better so that a CSV task can be added by simple discovery of a gem, but an alternative is to look for a `.i18n-tasks.rb` file that can be loaded, rather than looking in the config file.

**Comment by glebm** [comment]
Hi, thanks for reporting this, should be fixed in v0.8.5. I've had a look at Minitest and I prefer this explicit approach over what minitest does (`Gem.find_files("minitest/*_plugin.rb")`).
