### ISSUE TITLE
Cannot ignore

### ISSUE THREAD

**Issue by kazmin** [glebm/i18n-tasks#154]
Hey,
base_locale: bg
locales: [bg, en]
ignore_missing:
    - date.*

Missing translations (32) | i18n-tasks v0.8.3

|   en   | date.abbr_day_names                               | bg ["НЕД", "ПОН", "ВТО", "СРЯ", "ЧЕТ", "ПЕТ", "СЪБ"]                                                                                |
|   en   | date.abbr_month_names                             | bg ["ян.", "фев.", "март", "апр.", "май", "юни", "юли", "авг.", "сеп.", "окт.", "ноем.", "дек."]                                    |
|   en   | date.day_names                                    | bg ["неделя", "понеделник", "вторник", "сряда", "четвъртък", "петък", "събота"]                                                     |
|   en   | date.formats.default                              | bg %d.%m.%Y                                                                                                                         |
|   en   | date.formats.long                                 | bg %d %B %Y                                                                                                                         |
|   en   | date.formats.short                                | bg %d %b                                                                                                                            |
|   en   | date.month_names                                  | bg [nil, "януари", "февруари", "март", "април", "май", "юни", "юли", "август", "септември", "октомври", "ноември", "декември"]      |
|   en   | date.order                                        | bg ["year", "month", "day"]                                                                                                         

those elements are provided by default in the english locale, I want to ignore them, but it doesn't work. What am I doing wrong?

**Comment by glebm** [comment]
Hi, I cannot reproduce this. Please make sure you are using i18n-tasks 0.8.7 or 0.9.0.rc2 and double-check the yaml syntax (e.g. by checking the output of `i18n-tasks config`)
