### ISSUE TITLE
Relative keys with mailers do not prepend method name

### ISSUE THREAD

**Issue by lowjoel** [glebm/i18n-tasks#155]
Mailers act like controllers (indeed, they inherit from ActionController::Base), but using relative keys in mailers would trigger an untranslated key+unused key error pair because the method names are not factored in.

The immediate fix I see is in lib/i18n/tasks/scanners/pattern_scanner.rb, replace:
```ruby
    def controller_file?(path)
      /controllers/.match(path)
    end
```
with 
```ruby
    def controller_file?(path)
      /mailers|controllers/.match(path)
    end
```

**Comment by glebm** [comment]
Hi, I've just merge @tomoasleep's branch, so this should be resolved on master

**Comment by lowjoel** [comment]
Thanks @glebm!

**Comment by tomoasleep** [comment]
I'm glad that my patch helps :-)

**Comment by glebm** [comment]
@tomoasleep Thanks!
