### ISSUE TITLE
XLSX reports are not compatible with OSX Numbers.app

### ISSUE THREAD

**Issue by rstacruz** [glebm/i18n-tasks#159]
the `bundle exec i18n-tasks xlsx-report` task produces an Excel sheet not compatible with Numbers.app on a Mac (using axlsx 2.0.1).

![pasted_image_7_30_15__6_27_pm](https://cloud.githubusercontent.com/assets/74385/8981153/ac6dab70-36e8-11e5-8d33-a32a152d18f6.png)

**Comment by rstacruz** [comment]
How about an option to export to CSV instead?

**Comment by rstacruz** [comment]
Oh, and axlsx 2.1.0.pre produces the same result.

**Comment by rstacruz** [comment]
According to axlsx docs:

> Numbers
> you must set 'use_shared_strings' to true. This is most conveniently done just before rendering by calling Package.use_shared_strings = true prior to serialization.

**Comment by glebm** [comment]
Hi @rstacruz! Thank you for reporting this. I will verify the PR later tonight and merge it.
Note that you can export/import CSV with these custom tasks: https://github.com/glebm/i18n-tasks/wiki/Custom-CSV-import-and-export-tasks.

**Comment by glebm** [comment]
v0.8.6 is now out with the fix!
