### ISSUE TITLE
existing translations reported as missing

### ISSUE THREAD

**Issue by oinak** [glebm/i18n-tasks#166]
I used `i18n-tasks health` to search for missing and unused translations but it reported existing/working translations as missing:

![report and traslations greped](http://snag.gy/BhuZN.jpg)

Let me know if I you need any further details to pinpiont the issue

**Comment by glebm** [comment]
Hola! By default, i18n-tasks only reads files under `config/%{locale}.yml`. Please uncomment https://github.com/glebm/i18n-tasks/blob/master/templates/config/i18n-tasks.yml#L18-L21 and try again.

**Comment by oinak** [comment]
Thanks, I must have overlooked that from the Readme, I see now it at https://github.com/glebm/i18n-tasks#multiple-locale-files
Sorry for bothering

**Comment by oinak** [comment]
closed because it works and is documented and I am blind :see_no_evil:

**Comment by glebm** [comment]
The documentation could use improvement, it points you to the config file, but should mention this gotcha explicitly. Will update, thanks!
