### ISSUE TITLE
Is it possible to detect duplicate keys in one file?

### ISSUE THREAD

**Issue by thbar** [glebm/i18n-tasks#167]
Currently if I run `health` it does not warn me about potential duplicate keys. Is there still a way to achieve that? Thanks!

**Comment by glebm** [comment]
The duplicate *keys* are removed automatically when you run normalize. The duplicate *values* across locales are usually not a bug (many languages share words), but can be found with `i18n-tasks eq-base`.

**Comment by thbar** [comment]
I'll try `normalize` and a git diff should work then. Thanks! Should I close the issue?

**Comment by glebm** [comment]
Yes, please close it if it works. :+1:
