### ISSUE TITLE
'language.no' is treated as if it was 'language.false' !?

### ISSUE THREAD

**Issue by Dschee** [glebm/i18n-tasks#168]
When I run `i18n-tasks health` I get this along 'Unused keys':
``` ruby
  en   | language.name.false | Norwegian 
```

Here's how I add it:
``` ruby
# i18n-tasks-use t('language.name.no')
```

Seems like `no` is treated like `false` somehow. Also when I run `i18n-tasks add-missing` I get a `false` translation key.

**Comment by glebm** [comment]
In YAML, `no` is treated as a boolean if unquoted: http://yaml.org/type/bool.html
Try quoting it?

**Comment by Dschee** [comment]
That might be true for values in YAML, but I wonder if it is also true for keys?
And if so, i18n-tasks still shouldn't replace 'languages.name.no' with 'languages.name.false'. To be more concise, here's what I would expect in the YAML:
``` YAML
en:
  language:
    name:
      'no': Norwegian
```

But what I get is:
``` YAML
en:
  language:
    name:
      false: Norwegian
```
I don't think this is the wanted behavior. Correct me if I'm wrong, though.

**Comment by glebm** [comment]
It is true for both keys in values, as you can verify by trying to `YAML.load('{no: 1}')`. `i18n-tasks` simply uses the YAML.load and dump, so `no` is parsed as `false` and saved as `false`. They key is nor "renamed" as both `no` and `false` are false.

**Comment by Dschee** [comment]
So I need to do it like this?

``` ruby
# i18n-tasks-use t("language.name.'no'")
```

Or alternatively like this?

``` ruby
# i18n-tasks-use t("'no'", scope:[:language, :name])
```

Did I understand it correctly?

**Comment by glebm** [comment]
No, you need the quotes in the YAML file.

**Comment by Dschee** [comment]
Okay, but then it's exactly what I'm saying: The task `i18n-tasks add-missing` should add those quotes to the keys – but it's just changing the 'no' to a 'false' – which is completely unexpected. As I stated above, my expected results would be `'no': Norwegian` in the YAML file, but I get `false: Norwegian`.

**Comment by glebm** [comment]
You are specifying a boolean key that is not used. You are using a string key that does not exist. I am not sure how to explain it better.

**Comment by Dschee** [comment]
I'm not specifying anything in the YAML file – I'm only adding this to my code:

``` ruby
# i18n-tasks-use t('language.name.no')
```

Then I run `i18n-tasks add-missing` which has this resulting YAML file:

``` YAML
en:
  language:
    name:
      false: Norwegian
```

Maybe I didn't succeed in clarifying this earlier. Sorry for that. But do you understand my problem now?

**Comment by glebm** [comment]
I see, I have just tried that and I cannot reproduce this behaviour.
It is adding the correct quoted key, using the latest 0.8 release.

What version of i18n-tasks and ruby are you using?
In the console, if you type YAML, does it say Psych?

```console
> YAML
=> Psych
```

**Comment by Dschee** [comment]
I use v0.8.7 and get the exact same result as you do when typing `bundle exec i18n-tasks irb` and `YAML` – yes, 'Psych'. 
---
Okay, I just tried again and now it works. That's crazy though and I don't what what of my changes made it work again – but seems like not happening any more. Can't explain why it happened. [Here](https://github.com/Flinesoft/MovieAssistor)'s the project where it happened in case someone wants to look deeper inside. It happened before [this](https://github.com/Flinesoft/MovieAssistor/commit/a8c1a6beb3a2c1d12876d964087c571818fddcf7) commit.
