### ISSUE TITLE
Expected output formatting

### ISSUE THREAD

**Issue by toxaq** [glebm/i18n-tasks#174]
Firstly apologies if this is the wrong place to ask but I was just wondering if the following was expected output syntax:

    ---
    "en":
      "app":
        "buttons":
          "edit": >-
            Edit

Compare to the standard Rails yaml examples, this seems overly verbose.

    en:
      app:
        buttons:
          edit: 'Edit'

I've looked into Psych to see what can be changed but can't work out what options would need to passed in to disable quoting keys and breaking lines. Am I missing something or being picky?

**Comment by glebm** [comment]
What you are using is not normal. For example, this is i18n-tasks' own [locale file](https://github.com/glebm/i18n-tasks/blob/8a7270be1a6d4d5803d1c65e45d10e1b327a264e/config/locales/en.yml). Are you sure you are using Psych?

**Comment by toxaq** [comment]
Hi, yes I am. It's a big project, so maybe somethings throwing the config somewhere...

    $ i18n-tasks irb
    i18n-tasks v0.8.7 IRB
    Type guide to learn more
    2.1.5 :001 > YAML
     => Psych 

What you're showing is exactly what I want, if I could only work out what's wrong!

**Comment by glebm** [comment]
What does `i18n-tasks config data` show?

**Comment by toxaq** [comment]
As below

    $ i18n-tasks config data
    data:
      adapter: I18n::Tasks::Data::FileSystem
      read:
      - config/locales/app.%{locale}.yml
      - config/locales/dictionary.%{locale}.yml
      write:
      - config/locales/%{locale}.yml
      yaml:
        write:
          line_width: -1

**Comment by glebm** [comment]
The config is correct. Perhaps something is monkey-patching YAML?

```ruby
$ i18n-tasks irb
> YAML.ancestors
#=> [Psych]
```

**Comment by toxaq** [comment]
$ i18n-tasks irb
    i18n-tasks v0.8.7 IRB
    Type guide to learn more
    2.1.5 :001 > YAML.ancestors
    => [Psych] 

So crazy... If I yaml dump in IRB I get the expected too!

**Comment by glebm** [comment]
Time to debug with breakpoints! Serialization happens here: https://github.com/glebm/i18n-tasks/blob/master/lib/i18n/tasks/data/adapter/yaml_adapter.rb#L20

**Comment by toxaq** [comment]
Sweet, thanks for your help, the pointer and the gem! I'll get back to you when I find out what's going on.

**Comment by toxaq** [comment]
Soi, if I just dump the yaml at that point `tree.to_yaml` the output is correct. Is there any processing going on after that? I don't think Psych is the issue at all here...

**Comment by glebm** [comment]
No processing happens after that. 
Does running `i18n-tasks normalize` vs `bundle exec i18n-tasks normalize` lead to different output?

**Comment by glebm** [comment]
Also, perhaps a breakpoint here: https://github.com/glebm/i18n-tasks/blob/8a7270be1a6d4d5803d1c65e45d10e1b327a264e/lib/i18n/tasks/data/file_formats.rb#L42

**Comment by toxaq** [comment]
Dumped out there, looked the same, reverted my translations, ran it one last time for luck and boom, exactly what I'd hoped for the first time. I'm none the wiser! Thanks again for your help.

**Comment by glebm** [comment]
Could have been some encoding issue or something

**Comment by toxaq** [comment]
Good point.

**Comment by toxaq** [comment]
So, an update. After finalling getting add-missing to work as expected for an unknown reason, I finally ran translate missing and low and behold, the error is back. It seems as I patched yaml_adaptor to use tree.to_yaml() instead of passing the options it's ok but as soon as it's un-patched... 

I wonder if EasyTranslator is doing something global?

**Comment by glebm** [comment]
EasyTranslate does not touch yaml. Do you know which key/value/language is causing the issue?

**Comment by toxaq** [comment]
No, I'm a bit stumped as to how to isolate it. Even if I cut it down to just one line, it still borks the French version...

**Comment by glebm** [comment]
So there is a key/value an English that alone breaks when translated to French? That's good news, means I can try to reproduce?

**Comment by toxaq** [comment]
Hmm, I have a feeling it must be something crazy due to my setup. I can't imagine you can reproduce from this

    ---
    en:
      edit: Edit

Running `i18n-tasks translate-missing fr` becomes

    ---
    "fr":
      "edit": >-
        Modifier

Hmmm...

**Comment by glebm** [comment]
Tried that with v0.8.7 and v0.9.0, can't reproduce.

**Comment by toxaq** [comment]
Yeah, that's what I suspected. If I dump `hash = tree.to_hash(true)` in write_tree, it's correct, after passing through the yaml adaptor it's going crazy. Wondering if some library has monkey patched somewhere. Totally nothing wrong in this gem as best I can tell...

**Comment by glebm** [comment]
Are you on OSX or Linux? `file config/locales/fr.yml` should show ASCII or UTF-8

**Comment by toxaq** [comment]
OSX, that returns `ASCII text`

**Comment by glebm** [comment]
How about `Psych::LIBYAML_VERSION`? Reports 0.1.6 here.

**Comment by toxaq** [comment]
2.1.5 :001 > Psych::LIBYAML_VERSION
     => "0.1.6" 

So, crazy time, if I remove `line_width: -1` from the config file, it works fine.

**Comment by glebm** [comment]
Whoa.

**Comment by toxaq** [comment]
I know right!

**Comment by glebm** [comment]
What's the Psych version?

**Comment by toxaq** [comment]
2.0.13

**Comment by glebm** [comment]
It's a bug in Psych! Mine is 2.0.8, after upgrading to 2.0.15 it reproduces!

**Comment by toxaq** [comment]
Heh, crazy! I was just going through the Psych github to see if anything was in it... Well nice to have a sort of resolution on this and know I'm not too crazy.

**Comment by glebm** [comment]
I will look into fixing this later, but for now reported as https://github.com/tenderlove/psych/issues/254, possibly caused by https://github.com/tenderlove/psych/commit/2edf642b82ae88ed93ec5f6ed7ae699771c04fc6.

**Comment by glebm** [comment]
Nice to have this resolved.

![This is fine meme template](http://i1.kym-cdn.com/entries/icons/original/000/018/012/Screen_Shot_2015-05-12_at_3.31.31_PM.png)

Programming is fine.

**Comment by toxaq** [comment]
Haha, nice work :)

**Comment by WaKeMaTTa** [comment]
Conclusion:

```yaml
data:
  adapter: I18n::Tasks::Data::FileSystem
  yaml:
    write:
      # line_width:
```

to have the same formatting as rails.
