### ISSUE TITLE
How to disable AST scanner?

### ISSUE THREAD

**Issue by ajb** [glebm/i18n-tasks#181]
It seems like the AST scanner is having a bit of trouble parsing out keys from [Erector](https://github.com/erector/erector) views, which have a `.rb` extension. I'd like to disable the scanner to see if this is indeed the case, but I can't quite figure out how to do so in the configuration. Is there a way to do this with the config or in an initializer?

Thanks!

**Comment by glebm** [comment]
You can set the `search.scanners` setting explicitly (see the right format for this by running `i18n-tasks config`), e.g.:

```yaml
search:
  scanners:
  - - "::I18n::Tasks::Scanners::PatternWithScopeScanner"
    - ignore_lines:
        rb: "^\\s*#(?!\\si18n-tasks-use)"
        opal: "^\\s*#(?!\\si18n-tasks-use)"
        haml: "^\\s*-\\s*#(?!\\si18n-tasks-use)"
        slim: "^\\s*(?:-#|/)(?!\\si18n-tasks-use)"
        coffee: "^\\s*#(?!\\si18n-tasks-use)"
        erb: "^\\s*<%\\s*#(?!\\si18n-tasks-use)"

**Comment by ajb** [comment]
Thanks!
