### ISSUE TITLE
Problems when using Ruby 2.3's safe navigation operator

### ISSUE THREAD

**Issue by lucascaton** [glebm/i18n-tasks#182]
By adding a `&.`, aka. **safe navigation operator** (released in [Ruby 2.3.0](https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/)), it causes the following error:

`i18n-tasks: Error scanning <file>: unexpected token tDOT`

**Comment by glebm** [comment]
A stable version of the parser gem with 2.3.0 support should be out soon, but for now please try adding this to your Gemfile:

```ruby
gem 'parser', '~> 2.3.0.pre.6'
```

**Comment by lucascaton** [comment]
@glebm thanks!

**Comment by glebm** [comment]
Parser 2.3.0.1 is out!
