### ISSUE TITLE
ruby dependency

### ISSUE THREAD

**Issue by dancinglightning** [glebm/i18n-tasks#184]
There was a ruby dependency introduced in a minor version 
0.9.1 all of a sudden required ruby 2.1
this seems very arbitrary, and at least should require a major version

Why is this done ? What about 2.0 or even 1.9 stops working?

**Comment by glebm** [comment]
i18n-tasks uses keyword arguments which 1.9 doesn't have, and it also uses required keyword arguments which didn't make it to 2.0.

**Comment by dancinglightning** [comment]
also uses new hash syntax already in 0.9.0 which as a result doesn't actually work with 1.9

**Comment by glebm** [comment]
yes, can't update gem metadata for already released gems though.
if this is causing a problem with your project, note that you can use an entirely separate ruby version for running i18n-tasks, as it only performs static analysis.

Would recommend upgrading ruby though, as 1.9 reached EOL almost a year ago.
