### ISSUE TITLE
Missing translations due to extraneous space

### ISSUE THREAD

**Issue by lowjoel** [glebm/i18n-tasks#188]
```
+--------+----------------------------------------------------------------+-----------------------------------------------------------+
| Locale | Key                                                            | Value in other locales or source                          |
+--------+----------------------------------------------------------------+-----------------------------------------------------------+
|  all   | course.assessment.assessments.index. maximum_experience_points | app/views/course/assessment/assessments/show.html.slim:14 |
+--------+----------------------------------------------------------------+-----------------------------------------------------------+
```

show.html.slim:14:
```slim
        th = t('.maximum_experience_points')
```

I have no idea how this came about; 0.9.2 worked fine.

**Comment by glebm** [comment]
Great that the app is open source, this will be easy to debug. Looking into it now.

**Comment by glebm** [comment]
@lowjoel The problem is located here: https://github.com/Coursemology/coursemology2/blob/d9b333b3010fb88d692fbfe9d8f7e3a2e6fe0787/config/locales/en/course/assessment/assessments.yml#L21-L22.

This is parsed in YAML as a symbol with a space in it.

**Comment by lowjoel** [comment]
@glebm thanks! Maybe then the location should be better reported?

**Comment by glebm** [comment]
Well this would take some time to implement, but the next release will at least tell you that it's a reference key

**Comment by glebm** [comment]
Reference resolution is reported in the new release, v0.9.4:

![i18n-tasks-refs](https://cloud.githubusercontent.com/assets/216339/12867320/3f821812-cce2-11e5-9b92-844f8ad60926.png)

**Comment by lowjoel** [comment]
@glebm it would be awesome*r* if the location reported the reference location, too :smile:
