### ISSUE TITLE
i18n-tasks forces locale to :en

### ISSUE THREAD

**Issue by fab-girard** [glebm/i18n-tasks#190]
Hello,
I'm trying to run i18n-tasks before my test task. I've noticed i18n-tasks sets (forces) locale to :en at the end of task... (and for following tasks). I think it's a strange behavior, since I've set i18n.default_locale (or i18n.locale) to :fr in my config... I think i18n locale should be :fr at the end of i18n-tasks.
What is your point of view on this subject ?

Thanks for this gem !
Fabien

**Comment by glebm** [comment]
Thanks for reporting this!
