### ISSUE TITLE
add-missing task fails after I added videos/ to my assets directory.

### ISSUE THREAD

**Issue by gungorkocak** [glebm/i18n-tasks#194]
I have no clue why but after adding /videos directory into my assets, `add-missing` task is also trying to search for files in that directory.

When I call;
```sh
$ i18n-tasks add-missing
```

It gives me error:

```sh
i18n-tasks: Error scanning app/assets/videos/landing_video.mp4: invalid byte sequence in UTF-8
```

**Comment by glebm** [comment]
Exclude the app/assets/videos directory from search like in the commit above.
