### ISSUE TITLE
Health check fails with new Ruby 2.3 safe navigation operation (&.foo)

### ISSUE THREAD

**Issue by joeletizia** [glebm/i18n-tasks#195]
When I run a health check against my code base, the check will fail when parsing the new [safe navigation operator](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/).

Error received: 
`i18n-tasks: Error scanning app/models/filename.rb: unexpected token tDOT`

Example of file content that will fail: 
```ruby
class Foo
  def bar(baz)
    baz?.thing
  end
end
```

**Comment by glebm** [comment]
Try running:

```ruby
bundle update parser
```

**Comment by joeletizia** [comment]
This fixed my issue. Thanks for the help!
