### ISSUE TITLE
%{default} doesn't work in i18n-tasks tree-set-value

### ISSUE THREAD

**Issue by nilsine** [glebm/i18n-tasks#198]
When I try:
`i18n-tasks missing -f yaml fr | i18n-tasks tree-set-value %{default}`

I get "%{default}" as the value for the keys

**Comment by glebm** [comment]
Please use:

```ruby
i18n-tasks add-missing fr
```

Which is the same as:

```ruby
i18n-tasks add-missing fr --value '%{value_or_default_or_human_key}'
```

The default values live in the source code. The `tree-*` commands don't know about the source code. They operate only on trees given to them as arguments. I'd rather keep them clean of dependencies on the source code and translations data.
