### ISSUE TITLE
Version conflict of highline gem with Solidus

### ISSUE THREAD

**Issue by timrossinfo** [glebm/i18n-tasks#210]
The version of the `highline` gem (`>= 1.7.3`) used in this project conflicts with a different version `~> 1.6.18`) of the same gem defined in [Solidus Core](https://github.com/solidusio/solidus/blob/master/core/solidus_core.gemspec#L30).

I have removed the strict versioning of the `highline` gem on [my fork](https://github.com/LGWgo/i18n-tasks/commit/1c676ff1f919b5df0067542db1bc44407f2f7f96). The tests still pass and the library appears to work with the older version of the gem. Can we either remove the strict versioning, or allow older versions of this dependency?

**Comment by glebm** [comment]
It's fine to change it to `>= 1.6.18`, but why not bump the solidus dependency instead?

**Comment by timrossinfo** [comment]
Yes, that's a good point. I thought it might be better to enable `i18n-tasks` to work with older versions of the gem (unless a newer version is required), but 4 years is quite old! I will try bumping the version in Solidus and submitting a pull request.
