### ISSUE TITLE
`normalize` task converts `yes` string value to `true`

### ISSUE THREAD

**Issue by jessieay** [glebm/i18n-tasks#212]
I ran `i18n-tasks normalize` on my project and saw the following:

BEFORE
```
'no': no
'yes': yes
```

AFTER
```
'no': false
'yes': true
```

The task should be updated to interpret these as strings and not convert them to true/false

**Comment by glebm** [comment]
In YAML, `false` and `no` are both interpreted as the boolean `false` (http://yaml.org/type/bool.html).
If you want them to be interpreted as strings, you need to quote them.

**Comment by glebm** [comment]
And `i18n-tasks normalize` shouldn't change the type of the value because booleans in locale files are also a valid use case.

It is unfortunate that YAML has so many aliases for boolean.
