### ISSUE TITLE
i18n-tasks seems to ignore translations in dependencies

### ISSUE THREAD

**Issue by bertBruynooghe** [glebm/i18n-tasks#216]
I have this in my Gemfile: `gem 'rails-i18n'`, 
and keep on having warnings on missing `date.abbr_day_names` and `number.format.separator` while  they are defined in the gemfile...

**Comment by glebm** [comment]
By default, only the keys in `config/locales` directory are read.
See the config file `data.read` section if you want to add another gems locales: https://github.com/glebm/i18n-tasks/blob/915a84d6d06b637ce802f68b73e6271b41211189/templates/config/i18n-tasks.yml#L23

If you do that, most of the keys in `rails-i18n` will be considered unused, so you might want to also add them to `ignore_unused`.

**Comment by bertBruynooghe** [comment]
Thanks, that make sense!
(btw, wouldn't it make sense to never report unused locales in dependent-on gems as unused?)

**Comment by glebm** [comment]
Perhaps, but currently i18n-tasks doesn't understand such high level concepts as gems.
