### ISSUE TITLE
i18n_spec.rb runs extremely slow if SimpleCov is used

### ISSUE THREAD

**Issue by buren** [glebm/i18n-tasks#221]
`rspec spec/i18n_spec.rb` takes ~60 seconds to run *with* `SimpleCov` and ~2 seconds *without*. 

Haven't got the chance to dig deeper into it yet, but if I do I'll post the results back here.

**Comment by glebm** [comment]
https://github.com/colszowka/simplecov/issues/404

**Comment by buren** [comment]
Thanks 👑

**Comment by PragTob** [comment]
FYI it seems to mostly be the stdlib coverage library: https://github.com/colszowka/simplecov/issues/404#issuecomment-277443591

**Comment by dougo** [comment]
FYI this slowdown also happens when using just Ruby's builtin `Coverage` class, so it's not really a `SimpleCov` issue.
