### ISSUE TITLE
Use default translation value for missing keys

### ISSUE THREAD

**Issue by jmluque** [glebm/i18n-tasks#223]
Is there any way of using the default translation value when adding missing keys? For example:

`I18n.t('candidates.request_rejected', default: 'The request was rejected.')`

Would appear as:

`candidates:`
   `request_rejected: The request was rejected.`

Thanks in advance.

**Comment by jmluque** [comment]
It seems to do it fine on certain translaions (I think the ones that are on the controller) but not on all of them.

**Comment by glebm** [comment]
From Readme:

> ### Features and limitations
>
> `i18n-tasks` uses an AST scanner for `.rb` files, and a regexp-based scanner for other files, such as `.haml`.
>
> ✔ `default` argument can be used to pre-fill locale files (AST scanner only).

Does this answer your question?

**Comment by jmluque** [comment]
Yes, I missed that, thanks.
