### ISSUE TITLE
Using scope in rails views is broken

### ISSUE THREAD

**Issue by josepjaume** [glebm/i18n-tasks#224]
First of all, thanks for the good amount of work you've put in this gem. It works like a charm! It's definitely made my life easier :)

Since the `0.9.9` update, I'm experiencing issues when using `scope` in translations in my rails views.

Example:

```erb
# app/views/layouts/application.html.erb
<%= t(".title", scope: "specific") %>
```

This resolves to `specific.layouts.application.title` but while `0.9.8` works fine and picks it up, `0.9.9` doesn't detect it and my locales now show up as `unused`.

Is there anything I should take into account?

**Comment by josepjaume** [comment]
Wow, that was fast! 💃 

I don't know if it helps, but it looks like replacing it by: `<%= t(".title", scope: ["specific"]) %>` (using an array as a scope) makes it work.

**Comment by glebm** [comment]
Good catch! Fixed and released v0.9.10 :ship:

**Comment by josepjaume** [comment]
Hi @glebm! Thanks for such a quick fix!

There's still some scenarios where this is failing though. For example, I have this in my views:

```erb
<%= t "actions.manage", scope: "app.admin" %>
```

This should resolve to `app.admin.actions.manage` but it shows up as unused in my application.

I tried to run the test suite and fix it but couldn't manage to.

**Comment by glebm** [comment]
@josepjaume I tried to reproduce it but I can't. Are you sure you are on v0.9.10? What's in your config?

**Comment by josepjaume** [comment]
@glebm of course! Actually, the project is open-source, so you can check it yourself:

https://github.com/AjuntamentdeBarcelona/decidim/blob/50f10b677cfe2737cf54f0e7f978fa1665244781/decidim-admin/app/views/decidim/admin/features/index.html.erb#L7

The translation is found here:

https://github.com/AjuntamentdeBarcelona/decidim/blob/50f10b677cfe2737cf54f0e7f978fa1665244781/decidim-admin/config/locales/en.yml#L137

Take into account that we've structured the project into engines, so the configuration is found at:

https://github.com/AjuntamentdeBarcelona/decidim/blob/50f10b677cfe2737cf54f0e7f978fa1665244781/decidim-admin/config/i18n-tasks.yml

Thanks so much for your help!

**Comment by glebm** [comment]
Fix released in v0.9.11 :ship:

**Comment by josepjaume** [comment]
Awesome news! Thanks!! <3

**Comment by josepjaume** [comment]
Hi again! I'm sorry to be such a hassle, but there's still some instances where this is failing, although most of them got fixed.

This one is also reporting as missing:

https://github.com/AjuntamentdeBarcelona/decidim/blob/master/decidim-admin/app/views/decidim/admin/participatory_process_steps/index.html.erb#L6

We can work against a branch if you'd like, and keep iterating until they're all fixed :)

I tried to do this myself but to be honest I'm having a hard time understanding the internals :S

**Comment by glebm** [comment]
The nested calls are difficult to get to work with the current regexp parser that's used in the views. The best thing you can do is move this to a helper, then the AST parser will parse them correctly.

**Comment by josepjaume** [comment]
ok @glebm, thanks so much!

**Comment by glebm** [comment]
@josepjaume I've managed to fix the nested calls case as well but any further work should be done towards adding AST scanner support for various view formats. The regex hack is at its limits at this point.

**Comment by josepjaume** [comment]
Thanks @glebm! I can see how using regexp has its limits - been there with https://github.com/codegram/spinach and ended up writing a language parser.

Let me confirm it works and maybe you can release a new minor?

**Comment by josepjaume** [comment]
Confirmed! It chased all my use cases 💪 . Thanks so much!
