### ISSUE TITLE
Incorrectly scoping a nested layout

### ISSUE THREAD

**Issue by gavingmiller** [glebm/i18n-tasks#227]
I have the following code:

```
# app/views/configurations/foo.html.erg

<%= render layout: 'help_button', locals: { placement: 'left', pull: 'right' } do %>
  <h4><%= t('.title') %></h4>
  <%= t('.description_html') %>
<% end %>
```

Given the above, `.title` and `.description_html` are interpretted in rails as:

* `application.help_button.title`
* `application.help_button.description_html`

Due to the `help_button` partial being located in: `app/view/application/_help_button.html.erb`. 

This is handled in rails via [`scope_key_in_partial`](https://github.com/rails/rails/blob/56832e791f3ec3e586cf049c6408c7a183fdd3a1/actionview/lib/action_view/helpers/translation_helper.rb#L125). When running `i18n-tasks missing` the path of `configurations.foo.title` is returned as missing, instead of `application.help_button.title` as expected by rails.

-------

I'm happy to work on a fix for this, if indeed the root issue is in i18n-tasks.

**Comment by glebm** [comment]
`i18n-tasks` does only static analysis and not all cases can be easily resolved statically.

These should be absolute keys to make the code more obvious anyway.

**Comment by gavingmiller** [comment]
> these should be absolute keys to make the code more obvious.

This is a supported feature of rails - [see 4.1.4 "Lazy" Lookup](http://guides.rubyonrails.org/i18n.html). Whether it should be done one way or the other is a debate for the rails list, versus a tool that matches what happens in practice. If this is a case of won't fix, that's fine. It's just helpful to know whether my project can rely on this gem following spec or not.

**Comment by glebm** [comment]
> This is a supported feature of rails

I know.

> Whether it should be done one way or the other is a debate for the rails list

I'm just giving advice based on a decade of experience and dozens of large codebases, not starting a debate.

>  a tool that matches what happens in practice

The tool has limitations, that I've explained above.

> It's just helpful to know whether my project can rely on this gem following spec or not.

The limitations are outlined in the Readme. Only features that can be analysed statically are supported.

**Comment by gavingmiller** [comment]
Thanks for the clarification @glebm. Much appreciated and appreciate your work on this! ❤️
