### ISSUE TITLE
Detect overwritten keys

### ISSUE THREAD

**Issue by jeffblake** [glebm/i18n-tasks#229]
By mistake, I added a key called "errors". Naturally this overwrites all of the active record errors keys. It would be cool if this gem detected that a nested tree was overwritten by another key. I thought it detected this for me once before on a different key... but it doesn't do it for `errors`

**Comment by glebm** [comment]
i18n-tasks does detect it but it doesn't know about the activerecord keys unless you tell it by adding them to `data.read`.
