### ISSUE TITLE
hide google translate api key

### ISSUE THREAD

**Issue by ClaudioCarmeli** [glebm/i18n-tasks#231]
Hello,
I might be doing something wrong but I would like to translate with Google Translate. I added the key to the config file and it worked! Excellent.
```
## Google Translate
translation:
  # Get an API key and set billing info at https://code.google.com/apis/console to use Google Translate
  api_key: '1324jk23uho23jcoijx3iooxj32'
```
Now I would like to take it a step further and use an env variable instead of exposing the key. How can I do that? Changing the extension of the file from `.yml` to `.yml.erb` and adding the environment variable didn't work. Below is an example of what I added to my `config/application.yml` file.

```
GOOGLE_TRANSLATE_API_KEY: '1324jk23uho23jcoijx3iooxj32'
```

**Comment by glebm** [comment]
If you have an environment variable with that name, i18n-tasks will use it automatically.
However, `config/application.yml` (I'm not sure what that file is but I'm assuming some gem loads it and sets the environment from it) will not be picked up by i18n-tasks by default as it does not load your Rails app or any of its dependencies.

You can set it directly or via something like `~/.pam_environment`. E.g. this works:

```
GOOGLE_TRANSLATE_API_KEY=<your-key> i18n-tasks translate-missing
```

If you want to set it in `config/application.yml`, you have two options:
1. `<% require 'the gem that load config/application.yml' %>` on top of i18n-tasks.
2. In `config/i18n-tasks.yml`:

    ```yaml
    translation:
      api_key: <%= YAML.load_file('config/application.yml')['GOOGLE_TRANSLATE_API_KEY'].inspect
    ```

**Comment by ClaudioCarmeli** [comment]
Hi @glebm 
Thank you so much for your help. It worked straight away.
For anybody having the same issue, if you go with option 2, remember to close the erb tags.

eg.
```
translation:
  api_key: <%= ...... %>
```
