### ISSUE TITLE
de-normalize -p

### ISSUE THREAD

**Issue by ClaudioCarmeli** [glebm/i18n-tasks#232]
Hi,
Bizarre question:
What if, for any reason, (e.g. I need to google translate all my locales again for all languages) I wanted to put all of my translations in a single file (e.g. `en.yml` for English, `fr.yml` for French, etc) after having broken everything up into lots of files with `normalize -p`?

Is the gem already capable of this? I am curious to know.

**Comment by glebm** [comment]
I already replied here: https://github.com/glebm/i18n-tasks/issues/217#issuecomment-281199440
