### ISSUE TITLE
Prepended view paths

### ISSUE THREAD

**Issue by Frexuz** [glebm/i18n-tasks#236]
Hi. I'm using this code piece to split up my desktop and mobile views.
```
class ApplicationController < ActionController::Base
  before_action :set_view_paths

  def mobile_device?
    # ...
  end

  def set_view_paths
    prepend_view_path Rails.root.join('app', 'views', 'desktop')
    prepend_view_path Rails.root.join('app', 'views', 'mobile') if mobile_device?
  end
```

What happens when i run `add missing` is that all keys are scoped under a `dekstop:` and `mobile:` key, so basically each locale file has a full copy of itself.

Can't seem to figure out how to prevent it.. is it possible?

**Comment by glebm** [comment]
@Frexuz Set `search.relative_roots` in [config/i18n-tasks.yml](https://github.com/glebm/i18n-tasks/blob/master/templates/config/i18n-tasks.yml#L56).

**Comment by Frexuz** [comment]
Perfect :)
