### ISSUE TITLE
Support for identifying the use translations via It.it and It.plain

### ISSUE THREAD

**Issue by jufemaiz** [glebm/i18n-tasks#238]
Hi guys, apologies if this has been raised before.

Looking to discover a way to also capture keys used in translations via the [It](https://github.com/iGEL/it) gem.

Searching for "it" is somewhat problematic ><

**Comment by lime** [comment]
You should be able to configure the scanning pattern under `search.pattern` in `i18n-tasks.yml` (assuming you use the default scanner).

The default regex is pretty involved, and spread around over a couple of places, at least [here](https://github.com/glebm/i18n-tasks/blob/v0.9.13/lib/i18n/tasks/scanners/pattern_scanner.rb#L78-L88) and [here](https://github.com/glebm/i18n-tasks/blob/98454c437dd7f20af9d835bea0467b5aba1e8815/lib/i18n/tasks/scanners/ruby_key_literals.rb#L5-L12).

You could try to extract that pattern and extend it with `It.it`, `it` etc.

**Comment by lime** [comment]
I've had success in doing just that to make i18n-tasks recognize calls to `__('foo.bar')` in JS code.

The regex below is based on the default back in v0.8.2. The default seems to have changed since then, so if you want to have feature parity with the most recent version you'll have to do some digging in the code I linked to above.

```yml
search:
  pattern: (?<=^|[^\w'\-])(?:t(?:ranslate)?|__)[\(]\s*(:?".+?"|:?'.+?'|:\w+)
```

Hope it helps.

**Comment by glebm** [comment]
While there is no plugin for the [`it` gem](https://github.com/iGEL/it) yet, its support can be added easily with a monkey-patch like the one below:

```ruby
# lib/i18n/tasks/it.rb
require 'i18n-tasks'

module I18n::Tasks::Scanners
  PatternScanner.prepend Module.new do
    protected
    def translate_call_re
      Regexp.union(super, /(?<=^|[^\w'\-.]|[^\w'\-]It\.|It\.)it/)
    end
  end
  
  RubyAstScanner.class_eval do
    RECEIVER_MESSAGES = remove_const(:RECEIVER_MESSAGES) +
        [nil, AST::Node.new(:const, [nil, :It])].product(%i[it])
  end
end
```

```yaml
# config/i18n-tasks.yml.erb
<% require './lib/my_custom_scanner' %>
```

For now, I've added the monkey-patch above to the i18n-tasks wiki:
https://github.com/glebm/i18n-tasks/wiki/The-%22it%22-gem-support

**Comment by glebm** [comment]
I believe the commit above add all the necessary APIs to achieve this without monkey-patching:

```ruby
I18n::Tasks.add_scanner(
  '::I18n::Tasks::Scanners::RubyAstScanner',
  receiver_messages: [nil, AST::Node.new(:const, [nil, :It])].product(%i[it]),
  only: %w[*.rb]
)                      

I18n::Tasks.add_scanner(
  '::I18n::Tasks::Scanners::PatternWithScopeScanner',
  translate_call: /(?<=^|[^\w'\-.]|[^\w'\-]It\.|It\.)it/,
  exclude: %w[*.rb]
)
```

**Comment by glebm** [comment]
The following is now possible in v0.9.15:

```ruby
# lib/i18n_tasks_it.rb
# The "it" gem support for i18n-tasks
I18n::Tasks.add_scanner(
  '::I18n::Tasks::Scanners::RubyAstScanner',
  receiver_messages: [nil, AST::Node.new(:const, [nil, :It])].product(%i[it]),
  only: %w[*.rb]
)
I18n::Tasks.add_scanner(
  '::I18n::Tasks::Scanners::PatternWithScopeScanner',
  translate_call: /(?<=^|[^\w'\-.]|[^\w'\-]It\.|It\.)it/,
  exclude: %w[*.rb]
)
```

```yaml
# config/i18n-tasks.yml.erb
<% require './lib/i18n_tasks_it' %>
```

Someone should package this as a gem.

**Comment by jufemaiz** [comment]
You sir are awesome!!!
