### ISSUE TITLE
Support for I18n.localize

### ISSUE THREAD

**Issue by jufemaiz** [glebm/i18n-tasks#240]
Currently references to I18n.localize are not identified.

**Comment by ACPK** [comment]
+1

**Comment by glebm** [comment]
This is not feasible to resolve statically, see https://github.com/svenfuchs/i18n/blob/72303d929b4e12a726a6b974b52017e4bbe6b06f/lib/i18n/backend/base.rb#L72.

Use hints (`# i18n-tasks-use t('time.formats.shorts')`) next to your localize calls.

**Comment by jufemaiz** [comment]
Boh :(
