### ISSUE TITLE
command line option to specify location of config file

### ISSUE THREAD

**Issue by elrayle** [glebm/i18n-tasks#243]
### Request
Is it possible to add a command line option to specify the location of the config file?  

### Proposed:
```
i18n-tasks missing -cfg .internal_test_app/config/i18n-tasks.yml
i18n-tasks unused -cfg .internal_test_app/config/i18n-tasks.yml
```
using either a fully qualified path or relative.  Could be used with all commands, but minimally these two since they are part of the test suite.

### Context:  
We are using this for testing, but there is hesitation to ship with the config in the standard config directory since this isn't something that consumers of the gem should modify.  We generate a test app and put the` i18n-tasks.yml` file in `my_engine/.internal_test_app/config` directory instead of `my_engine/config`.  The tests are run from my_engine, so I modified the i18n_spec.rb to read the config file from the test app.  This works great.

In `my_engine/.internal_test_app/config/i18n-tasks.yml`, the only change from the default values is
```
read:
     - "<%= %x[bundle show my_engine].chomp %>/config/locales/**/*.%{locale}.yml"
```
### Problem: 
With the config in the test app and the locales in the engine config, the command line for missing and unused don't work.  

If I execute from the test app, missing and unused checks the test code against the engine's locales.  The test app code does not have the engine's code, so it always says that none are missing and all are unused.

If I execute from the engine, the default config is used and it doesn't look for files beyond en.yml (and similarly named translation files).  It doesn't find my_engine.en.yml.  In this case, it says all are missing and none are unused.

**Comment by glebm** [comment]
Do I understand correctly that you're working on an engine, and want to verify the engine's locales?

If so, why not just run the i18n-tasks tests from the engine directly?

Here are a couple of examples of engines that do this:
* https://github.com/thredded/thredded
* https://github.com/glebm/rails_email_preview

> We are using this for testing, but there is hesitation to ship with the config in the standard config directory since this isn't something that consumers of the gem should modify.

The stuff in the config directory is internal to the gem itself, it's not for modification (for example, `config/routes.rb`).

**Comment by elrayle** [comment]
I had it working that way originally.  I am part of a larger community that does not want the i18n-tasks.yml to be delivered with the engine.  If I am able to pass in the path to the yml file, it wouldn't matter that it is in an alternate location.

**Comment by glebm** [comment]
> I am part of a larger community that does not want the i18n-tasks.yml to be delivered with the engine

It is common to not want to ship certain files with the engine (such as tests), in order to reduce the gem size. The usual way to do this is to exclude the files you don't want in the gemspec, for example:

https://github.com/thredded/thredded/blob/master/thredded.gemspec#L18

**Comment by elrayle** [comment]
Thanks.  I'll take a look at that.  It would certainly be an easier approach.
