### ISSUE TITLE
support to read keys from react components (react-intl)

### ISSUE THREAD

**Issue by amf9t2** [glebm/i18n-tasks#244]
As react - rails are getting popular, is there any plan to get support to read keys from jsx file  [react-intl api](https://github.com/yahoo/react-intl/wiki/API#react-intl-api). 

Or is it possible with custom scanner and pattern matcher ?
I tried thinking custom scanner approach but no luck.

Thanks.

**Comment by glebm** [comment]
There is definitely no plans to support anything other than the i18n gem in the core.
However, it is possible to write a plugin for this. You'll need a custom data source and a custom scanner.

See the [wiki](https://github.com/glebm/i18n-tasks/wiki) for examples of plugins and custom scanners.
There are no examples of custom data sources that I'm aware of, but you can monkey-patch it by overriding [this method](https://github.com/glebm/i18n-tasks/blob/3f6b15dba894f7386c977e29ad0a70ac8ab14ba7/lib/i18n/tasks/data/file_system_base.rb#L140) in your plugin.
