### ISSUE TITLE
[question] spec if normalize would change some files

### ISSUE THREAD

**Issue by neumayr** [glebm/i18n-tasks#249]
Hey! 👋  

Would it be possible to add a spec to check if `i18n-tasks normalize` would apply changes to any `.yml` file(s). Sorry, for asking this question.

We run the `i18n_spec.rb` as part of our CI runner with every Pull Request. This works perfect, tests are failing if *'missing'* or *'unused'* keys are found. Some developer forgets to normalize i18n keys before commit. This sadly is not testable.

It's not tragic, it just adds noise/conflicts to other PRs that normalize the keys.
Could this be solved by some smart test? Maybe a `--dry` run or could `normalize` report a status[code] if files were changed/touched?

**Comment by glebm** [comment]
Hi, this would certainly be useful, PR welcome.

I'd suggest adding a new `check-normalized` command that:

1. Fails with a non-zero status code if there are non-normalized files.
2. Reports these files to stderr.
3. Is usable from `i18n_spec.rb`.

**Comment by glebm** [comment]
Released in v0.9.17!
