### ISSUE TITLE
Adapter not found for ERB files

### ISSUE THREAD

**Issue by mjgiarlo** [glebm/i18n-tasks#253]
@glebm I maintain a Rails engine that generates YAML translations into applications, and some of these are `.yml.erb` files. You can see an example here:

https://github.com/samvera/hyrax/blob/master/lib/generators/hyrax/work/templates/locale.de.yml.erb

When I ask `i18n-tasks` to add missing translations for these files, I (understandably) get the following error:

```
i18n-tasks: Adapter not found for lib/generators/hyrax/work/templates/locale.en.yml.erb. Registered adapters: [[:yaml, "*.yml", I18n::Tasks::Data::Adapter::YamlAdapter], [:json, "*.json", i18n::Tasks::Data::Adapter::JsonAdapter]]
```

How would you recommend I handle this? Is there a pattern you'd recommend? Would you prefer a PR, or should I handle this locally?

**Comment by glebm** [comment]
i18n-tasks does not support `.erb` locale files.

What you can do is:

1. Remove [this line](https://github.com/samvera/hyrax/blob/2a75adba3d31ba370d6c030b4be7ca037269e17a/config/i18n-tasks.yml#L23) from your config.
2. Add the keys in the `.erb` files to `ignore_missing`.

**Comment by mjgiarlo** [comment]
:ok_hand:, that'll do. Thanks, @glebm, for working on this super useful gem!
