### ISSUE TITLE
remove-unused don't remove whole files

### ISSUE THREAD

**Issue by vsakarov** [glebm/i18n-tasks#260]
I use `pattern_router` by default and have my translations split in couple of files for different components. But when I remove a component `remove-unused` always leaves some translations in the file and never removes it or leaves it empty. These leftovers are then reported as unused, but still can't be removed automatically as it should remove the file, but it doesn't. Another problem that may be related is when you have file that has no mapping in `write` section and all its translations are unused, `remove-unused` will leave it intact.

**Comment by glebm** [comment]
Can you demonstrate this by adding a failing integration test [here](https://github.com/glebm/i18n-tasks/blob/master/spec/i18n_tasks_spec.rb#L139)?

If not, there could be a problem in your config.

**Comment by vsakarov** [comment]
In order to demonstrate it I have to add new file in the fixtures which breaks a lot of tests for various reasons, but currently the relevant one is `remove_unused`. Here is the minimal diff I could write without modifying `i18n-tasks.yaml.erb`:

```diff
diff --git a/spec/i18n_tasks_spec.rb b/spec/i18n_tasks_spec.rb
index 7972c1e..c020200 100644
--- a/spec/i18n_tasks_spec.rb
+++ b/spec/i18n_tasks_spec.rb
@@ -360,6 +360,7 @@ resolved_reference_target.a (resolved ref)
 
     fs = fixtures_contents.merge(
       'config/locales/en.yml' => { 'en' => en_data }.to_yaml,
+      'config/locales/devise.en.yml' => { 'en' => { 'unused' => en_data['unused'] } }.to_yaml,
       'config/locales/es.yml' => { 'es' => es_data }.to_yaml,
       # test that our algorithms can scale to the order of {BENCH_KEYS} keys.
       'vendor/heavy.file'     => Array.new(BENCH_KEYS) { |i| "t('bench.key#{i}') " }.join
```

**Comment by glebm** [comment]
Thanks for the test case! I've tried to fix it in the commit linked above. Please try the version from `master`.

**Comment by vsakarov** [comment]
This fix is potentially dangerous as if someone adds external gem in read section of the config it may end up cleaning up gems.
Also the problem is bigger that this, I've managed to make normalize with pattern router leave old entries that become duplicates. I can open a new issue about this with tests if you like. Still not sure whether there is problem with data remove operations.

**Comment by glebm** [comment]
> This fix is potentially dangerous as if someone adds external gem in read section of the config it may end up cleaning up gems.

This was the behaviour before the fix as well.

> I've managed to make normalize with pattern router leave old entries that become duplicates.

Yes, please open a separate issue about the other issue.

**Comment by vsakarov** [comment]
You're right, thanks for fixing this one.
