### ISSUE TITLE
Documentation for renaming keys

### ISSUE THREAD

**Issue by mjgiarlo** [glebm/i18n-tasks#274]
The [compose tasks](https://github.com/glebm/i18n-tasks#compose-tasks) section of the README currently suggests using the deprecated `tree-rename-key` command to remove all keys in one locale that do not exist in another:

> $ i18n-tasks missing -t diff -f yaml en | i18n-tasks tree-rename-key en fr | i18n-tasks data-remove

Invoking the same commands using `tree-mv` instead of `tree-rename-key`, however, does not yield the expected results. If e.g. removing crufty `de` keys based on `en`, I'd expect the output of the second operation in the pipe to show the root key changing from `en` to `de`; instead, I see:

```yaml
en:
  de:
    etc:
```

Upon a very quick inspection, it seems this may be caused by `root: false` here: https://github.com/glebm/i18n-tasks/blob/2070f084cb8ec7e45509ce3d01b8e538516141e5/lib/i18n/tasks/command/commands/tree.rb#L71

(I am using `tree-rename-key` for my needs in the meantime, so I don't currently have cycles to try tweaking `root` to `true` to see what happens.)

**Comment by glebm** [comment]
Seems like a bug, all `tree-` commands should accept full keys (with `root: true`).

**Comment by mjgiarlo** [comment]
Thanks, @glebm!
