### ISSUE TITLE
When keys are used in a decorator i18n-tasks doesn't find them

### ISSUE THREAD

**Issue by dylanjha** [glebm/i18n-tasks#282]
```rb
class PostDecorator
  def label
     object.title + ' - ' + h.t('post.name')
  end
end
```

```yml
en:
  post:
     name: blog post
```

Running i18n-tasks health  will show:

```
Unused keys (1) | i18n-tasks v0.9.21
+--------+----------------------------------+----------------------+
| Locale | Key                              | Value
+--------+----------------------------------+-------------------------
|   en   | post.name             | blog post
```

This key is being used, so I would expect i18n-tasks to find it

**Comment by Lupeipei** [comment]
maybe you should check in your ` i18n-tasks,yml` file,  make sure the **search  paths** includes the file that used key post.name @dylanjha

**Comment by glebm** [comment]
h.t is not a pattern that i18n-tasks includes by default. See the config file for information on how to add it.
