### ISSUE TITLE
Unused task output broken

### ISSUE THREAD

**Issue by pdavid0** [glebm/i18n-tasks#284]
Ran `i18n-tasks health` which runs `i18n-tasks unused`. 

`macOS 10.13.4`
`iTerm2 3.1.5`
`=* ruby-2.3.7 [ x86_64 ]`

<img width="1440" alt="screen shot 2018-04-02 at 1 37 30 pm" src="https://user-images.githubusercontent.com/1034292/38207253-1cfe95fe-367b-11e8-9ea6-d652fb0ce23a.png">

Expected : output should be the same across all tasks.

Thanks :)

**Comment by glebm** [comment]
It's not exactly broken, you simply happen to have a *very* long key that doesn't fit in the terminal.

You can print it in another format, e.g.:

```
i18n-tasks unused -f yaml
```
