### ISSUE TITLE
Rails 5.2.0 support

### ISSUE THREAD

**Issue by pedrofurtado** [glebm/i18n-tasks#285]
Rails 5.2.0 is out and stable. Could you upgrade the Rails dependency version to 5.2?

**Comment by glebm** [comment]
i18n-tasks does not depend on Rails, only on ActiveSupport, and is compatible with all ActiveSupport versions starting from 4.0.2

**Comment by pedrofurtado** [comment]
@glebm Thanks for feedback!

You are right. It's another gem that is blocking the update of rails dependency in my project.

Thanks again!
