### ISSUE TITLE
Is it possible to run the `health` command without checking for normalization?

### ISSUE THREAD

**Issue by gregoirenovel** [glebm/i18n-tasks#290]
The README says:
> i18n-tasks health checks if any keys are missing or not used, and that all the locale files are normalized

I'd like to run this command but not check "that all the locale files are normalized", is it possible?

I looked for similar issues and dug around the code, without finding anything that might look like this.

Thanks!

**Comment by glebm** [comment]
Health simply runs missing, unused, and check-normalized:

https://github.com/glebm/i18n-tasks/blob/fa4202798c12475e908688b8fc659972612968b3/lib/i18n/tasks/command/commands/health.rb#L19

There is no option to skip `check-normalized` but you can run `missing` and `unused` directly instead:

```bash
if i18n-tasks missing; then i18n-tasks unused; else { i18n-tasks unused; false }; fi
```

**Comment by gregoirenovel** [comment]
Perfect, I'll do that then. Thanks a lot!
