### ISSUE TITLE
Skip `ignore_missing` for keys in a specific file

### ISSUE THREAD

**Issue by n00ge** [glebm/i18n-tasks#295]
I'm looking to keep a separate `en.yml` file with keys that do not need to be added to other languages (at the moment). I see it is possible to have the config file be `i18n-tasks.yml.erb` to support ruby. 

Is there a way for me to output an array under `ignore_missing` listing all the keys defined in a specific file? 

Essentially, I'd keep a file `config/en.yml` with keys that do need to be across all languages (currently `en` and `es`) and a separate file such as `config/en_only/en.yml` which other languages don't need. I was digging around in the gem to see how to get a list of keys but didn't find it. 

Thanks!

**Comment by glebm** [comment]
You can use `I18n::Tasks::Data::Tree::Siblings` to get a list of keys from a hash:

```erb
<%= YAML.dump(
      I18n::Tasks::Data::Tree::Siblings
        .from_nested_hash(YAML.load_file('config/locales/en_only/en.yml'))
        .keys.map { |key, _node| key }) %>
```

**Comment by n00ge** [comment]
Awesome, thanks for sharing!
