### ISSUE TITLE
Detect misused variables based on reference locale

### ISSUE THREAD

**Issue by Gargron** [glebm/i18n-tasks#303]
Would this be something you'd want to have in i18n-tasks? If there is a master locale, and it uses certain variables in certain keys, ensure that all other locales use the same variables in the same keys.

Use case: We use Weblate on Mastodon to let people submit translations. Some people translated variable names, thereby breaking some of Mastodon's pages when viewed in those languages. It's very hard to detect when this happens.

**Comment by glebm** [comment]
Sure, PR welcome. Consider adding a separate task, e.g. `check-consistent-interpolations`, (no strong opinion on the name) that also runs on `health` and has an ignore list.
