### ISSUE TITLE
i18n-tasks 0.9.28 forces I18n.enforce_available_locales to 'false' regardless of initial setting

### ISSUE THREAD

**Issue by tjgrathwell** [glebm/i18n-tasks#315]
In the most recent version, [loading the 'i18n/tasks' file forces `I18n.enforce_available_locales` to `false`](https://github.com/glebm/i18n-tasks/commit/efcc22c022373e5258ac8fb88dc601ea37abdeb2#diff-c6f4e954117dd947c004253307ae713bR74)

This caused an order-dependent test failure in our build since we load `i18n/tasks` late and have some other tests that depend on `I18n.enforce_available_locales` being `true`.

I think the gem should be changed to ensure `enforce_available_locales` remains whatever the original value was. But I don't know why the gem is setting it to `true`, so I can't propose a precise solution. If `enforce_available_locales` need to be off for some tests or features, the toggling of it should probably be in those tests or features rather than globally.

**Comment by glebm** [comment]
It's set to `false` here, I'm not sure why:

https://github.com/glebm/i18n-tasks/blob/efcc22c022373e5258ac8fb88dc601ea37abdeb2/lib/i18n/tasks.rb#L74

@Gargron PTAL

**Comment by Gargron** [comment]
We are retrieving pluralization data for various language files, but without that line, I18n complains that those languages are not available. Pluralization is, I believe, the only case of us using `I18n.t`, so the problem does not come up in other cases. The reason as I understand it is that while we load all language files of the underlying application, we don't set the available locales anywhere.

**Comment by glebm** [comment]
Can we restore `enforce_available_locales` after loading?
