### ISSUE TITLE
Normalization adds whitespaces

### ISSUE THREAD

**Issue by Antronin** [glebm/i18n-tasks#319]
When I run ```i18n-tasks normalize``` it adds whitespaces to the end of below lines:
```
  date:
    abbr_month_names:
    -  <-- whitespace added to the end of the line
    - Jan
    - Feb
```
But I would like to remove all whitespace at line endings. Is there a solution?

**Comment by glebm** [comment]
Perhaps you'd have to run some post-processing.
YAML serialization is handled entirely by Psych, so I suggest you file an issue there. https://github.com/ruby/psych

**Comment by Antronin** [comment]
Thnax. I submitted an Issue for Psych:
https://github.com/ruby/psych/issues/394
