### ISSUE TITLE
Support i18n-tasks-use hints within JavaScript comment lines

### ISSUE THREAD

**Issue by cbeckr** [glebm/i18n-tasks#322]
i18n-tasks does not pick up i18n-tasks-use hints written in JavaScript, e.g.:
```
// i18n-tasks-use t('some.key')
```
The reason for this lies in RubyAstScanner's ```MAGIC_COMMENT_PREFIX```, which looks as follows: ```/\A.\s*i18n-tasks-use\s+/```.
The first dot is assuming a single comment character, so the line does not get picked up.

**Comment by glebm** [comment]
`RubyAstScanner` is only used to scan `.rb` files.
For `.js` and other files, the following mapping is used instead:

https://github.com/glebm/i18n-tasks/blob/e2ffb334d79e5d61fb726dfefc7b4ced61ccb9f7/lib/i18n/tasks/scanners/pattern_scanner.rb#L16-L22

PR welcome

**Comment by glebm** [comment]
Note that magic comments *are* actually supported but the call must match the following pattern:

https://github.com/glebm/i18n-tasks/blob/e2ffb334d79e5d61fb726dfefc7b4ced61ccb9f7/lib/i18n/tasks/scanners/pattern_scanner.rb#L15

**Comment by zealot128** [comment]
Thanks for the tip. Because the IGNORE_LINES is frozen, i cannot modify IGNORE_LINES directly, but have to inherit from PatternScanner and reset it in an initializer.

```ruby
class JsScanner < I18n::Tasks::Scanners::PatternScanner
  IGNORE_LINES = I18n::Tasks::Scanners::PatternScanner::IGNORE_LINES.merge(
    'js' => re=%r{^\s*// *(?!\si18n-tasks-use)}, 
    'ts' => re
  )
  def initialize(**args)
    super
    @ignore_lines_res = (config[:ignore_lines] || IGNORE_LINES).each_with_object({}) do |(ext, re), h|
      h[ext.to_s] = Regexp.new(re)
    end
  end
end
I18n::Tasks.add_scanner 'JsScanner', only: %w(*.js *.ts)
```

To make globs work in the use, one cannot use "*" but must simulate ruby in the comment:

```javascript
// i18n-tasks-use t("js.feedback.behavior.options.#{key}")
$t("...")
