### ISSUE TITLE
i18n-tasks: unknown command: csv-export

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [glebm/i18n-tasks#338]
I just tried to make the csv export working (see https://github.com/glebm/i18n-tasks/wiki/Custom-CSV-import-and-export-tasks) but it fails:

```
i18n-tasks csv-export
=> i18n-tasks: unknown command: csv-export
```

also

```
i18n-tasks csv_export
=>i18n-tasks: unknown command: csv_export
``` 

doesn't work?

Any ideas why this is not working?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Whoopsie,

forgot following:

```
# config/i18n-tasks.yml
<% require './lib/i18n_csv_tasks' %>
```

Works now 👍

**Comment by glebm** [comment]
You can alternatively use the `i18n-tasks-csv` gem
https://github.com/halostatue/i18n-tasks-csv
