### ISSUE TITLE
Normalization adds whitespaces - inconsistently

### ISSUE THREAD

**Issue by sethherr** [glebm/i18n-tasks#355]
Running into an issue with inconsistent normalization on [Bike Index](https://github.com/bikeindex/bike_index).

Normalization is _not_ adding whitespace locally, and then is [failing on CircleCI](https://circleci.com/gh/bikeindex/bike_index/11655#tests/containers/2). Which is very frustrating.

I can't demonstrate that `normalize` is passing locally, but I promise that it is. Both local and CircleCI are running the same version of ruby, same version of gems, etc.

The end result of this is the same as #319 - but since i18n-tasks no longer uses Psych, and instead uses the standard lib yaml parser, I think this belongs in a separate issue.

I'm trying to solve this, hopefully I figure it out shortly and I'll update here when I do - but in case anyone else runs into this problem, I figure documenting it is worthwhile.

**Comment by sethherr** [comment]
I was not able to figure out a quick way of diagnosing what the difference was between the CircleCI and local parsing, and am just manually editing the files locally.

If there is a way to do additional diagnostics, or any way of getting to a fix on this, I would be very appreciative!

**Comment by AlexanderZagaynov** [comment]
I also bumped with this issue, here is how it looks on Travis:

<img width="605" alt="Screen Shot 2020-09-16 at 3 48 23 PM" src="https://user-images.githubusercontent.com/7778414/93346894-c082b200-f834-11ea-879e-ec853cae847c.png">

**Comment by rachid** [comment]
Exactly the same issue here!

**Comment by gueorgui** [comment]
Also bumped into this. Using Circle CI and Linux for local dev.

**Comment by spyrbri** [comment]
The problem lies in the yaml gem which behaves differently on different operating systems.

```ruby
# ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
# irb
irb(main):001:0> require "yaml"
=> true
irb(main):002:0> tree =  {"en"=>{"empty"=>nil}}.to_yaml
=> "---\nen:\n  empty: \n"
```

```ruby
# ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
# irb
irb(main):001:0> require "yaml"
=> true
irb(main):002:0>  tree =  {"en"=>{"empty"=>nil}}.to_yaml
=> "---\nen:\n  empty:\n"
```

**Comment by gueorgui** [comment]
Just did a quick test on my local machine (Arch Linux) and on the Circle CI VM. Different behaviours despite similar systems:

### Local:

```ruby
$ uname -a
Linux geofront 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux
$ ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
$ irb
irb(main):001:0> require "yaml"
=> true
irb(main):002:0> tree =  {"en"=>{"empty"=>nil}}.to_yaml
=> "---\nen:\n  empty:\n"
```

### Circle CI:

```ruby
circleci:~$ uname -a
Linux b2f5d83f5d3f 4.15.0-1077-aws #81-Ubuntu SMP Wed Jun 24 16:48:15 UTC 2020 x86_64 GNU/Linux
circleci:~$ ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
circleci:~$ irb
irb(main):001:0> require "yaml"
=> true
irb(main):002:0> tree =  {"en"=>{"empty"=>nil}}.to_yaml
=> "---\nen:\n  empty: \n"
```

One difference that I can see is the much older kernel version on the Circle CI VM.

**Comment by spyrbri** [comment]
The problem is with the libyaml versions. There is a difference on how the versions 0.2.4 and 0.2.5 handle the nil values.

An easy way to check the version of your libyaml version is the following:

 ```
# irb
irb(main):001:0> require "yaml"
=> true
irb(main):002:0> Psych.libyaml_version
=> [0, 2, 5]
```

**Comment by mvz** [comment]
Getting the correct libyaml version onto the current `ubuntu-latest` runner on GitHub Actions is quite involved. How about adding a small post-processing step to the normalization process that removes these trailing spaces, so the behavior is consistent no matter what version of libyaml is used?

**Comment by dssjoblom** [comment]
Having this problem as well
