### ISSUE TITLE
Find missing keys that contain spaces

### ISSUE THREAD

**Issue by bernb** [glebm/i18n-tasks#359]
Task `missing` does not find missing keys that contain spaces, example: `<%= t('some key') %>`. Those are however valid keys (at least for `I18n::Backend::ActiveRecord`) and they get found by the translation backend if translations are added.
Context (layout file):
```
    <div class="row">
      <div class="col-3">
        <dt><%= t('some key') %></dt>
      </div>
      <div class="col">
        <dd><%= @some_output %></dd>
      </div>
    </div>
```

**Comment by davidwessman** [comment]
@bernb What does your translation source look like?
