### ISSUE TITLE
Ignore Liquid / Flexible interpolations filter

### ISSUE THREAD

**Issue by espen** [glebm/i18n-tasks#368]
I use Liquid in my translation files. Is it possible to ignore these tags when using Google Translate?

Example:

`Reminder: Reservation {% if booking.service != nil %}of {{ booking.title }} {% endif %}{{ booking.booked_from }}.`

Spanish:
`Recordatorio: reserva {% if booking.service! = Nil%} de {{booking.title}} {% endif%} {{booking.booked_from}}.`

Danish:
`Påmindelse: Reservation {% hvis booking.service! = Nul%} af {{booking.title}} {% endif%} {{booking.booked_from}}.`

In both cases 'nil' is translated. In the Danish translation 'if' is also translated.

I see that this gem handles Rails i18n interpolations before passing it into EasyTranslate. Would it be possible for this to handle Liquid as well? Liquid can be both `{% code %}` and `{{ variable }}`.

**Comment by glebm** [comment]
As a workaround, you could override `I18n::Tasks::BaseTranslator::INTERPOLATION_KEY_RE` in `config/i18n-tasks.yml`

**Comment by espen** [comment]
That did the job, awesome! Thanks for a flexible gem :)
