### ISSUE TITLE
Code incompatible with ruby 3

### ISSUE THREAD

**Issue by mildred** [glebm/i18n-tasks#370]
https://github.com/glebm/i18n-tasks/blob/1d1f4205e66a48b41dda4225f29d7806674e0249/lib/i18n/tasks/command/dsl.rb#L13-L15

I believe it should be:

```ruby
 def t(*args, **kargs) 
   I18n.t(*args, **kargs) 
 end 
```

The error: ```i18n-1.8.8/lib/i18n.rb:196:in `translate': wrong number of arguments (given 2, expected 0..1) (ArgumentError)```

**Comment by MatthewKennedy** [comment]
I'm getting the same issues.

**Comment by glebm** [comment]
Released v0.9.34
