### ISSUE TITLE
Scope Not Being Picked Up With Custom Pattern Matcher

### ISSUE THREAD

**Issue by MatthewKennedy** [glebm/i18n-tasks#376]
When using:

```
# Spree PatternMapper
<% I18n::Tasks.add_scanner 'I18n::Tasks::Scanners::PatternMapper', patterns: [['\bSpree\.t[( ]\s*%{key}', 'spree.%{key}']] %>

```

The scope is not getting picked up, any idea how to fix this?

`<%= Spree.t(:my_key, scope: 'date_picker')%>`
returns `spree.my_key`
expected `spree.date_picker.my_key`

**Comment by MatthewKennedy** [comment]
I'm guessing this is due to the down scope.

**Comment by glebm** [comment]
Yeah, `scope` is not supported with `PatternMapper`. You could try adding support but it may be better to just avoid `scope:` altogether.
