### ISSUE TITLE
missing not working when using custom form builders

### ISSUE THREAD

**Issue by hidr0** [glebm/i18n-tasks#379]
Hello,

We have a custom form builder, which generates a label for every field:

Eg:

```
<%= f.text_field :title %>
```

Will generate a custom html, which inside will call `f.label` and thus need the key: `en.helpers.label.model.title`

Is there a way to tell the tool to look for these kind of fields, because I noticed that it does not do it I cannot resolve them easy?

**Comment by hidr0** [comment]
Whe I dug deeper I noticed that even

```
<%= f.label :title %>
```

does not generate the missing key for: `en.helpers.label.model.title`

Am I doing something wrong?

**Comment by hidr0** [comment]
In a brand new project the only two new gems I use are:

```
gem 'i18n-tasks', '~> 0.9.28'
gem 'i18n-debug', group: :development
```

The only html:
```
<%= form_for @user do |f| %>
    <%= f.label  :name %>
    <%= f.text_field  :name %>
    <%= f.submit %>
<% end %>

```

```
[i18n-debug] en.helpers.label.user.name => nil
[i18n-debug] en.helpers.label.user.name => nil
[i18n-debug] en.activerecord.attributes.user.name => nil
[i18n-debug] en.attributes.name => nil
[i18n-debug] en.activerecord.models.user => nil
```

`i18n-tasks missing`
`✓ Well done! No translations are missing.`

I need the translation to be missing, because then I would have to add it to my second language. Because now It is not added in the second language and my tests pass, but I do not have a translation.

**Comment by glebm** [comment]
i18n-tasks doesn't know what keys are used by these helpers. You can let i18n-tasks know either by passing the `t(...)` string explicitly or with an `i18n-tasks-use` comment https://github.com/glebm/i18n-tasks#fine-tuning

**Comment by hidr0** [comment]
Is there a way to write a custom parser? They are 4 field types max?
