### ISSUE TITLE
Not detecting keys with slashes

### ISSUE THREAD

**Issue by ryanb** [glebm/i18n-tasks#380]
It looks like keys with slashes are not detected. Is there a better way to handle these?

```
t("activerecord.attributes.product/categories.name")
```

ActiveRecord uses slashes for both namespaces and nested associations.

Note: This is a duplicate of #377 but that was closed. Not certain why.

**Comment by glebm** [comment]
This can probably be solved by adding the `/` here:
https://github.com/glebm/i18n-tasks/blob/881ed6f3d2aed94fa0aae050584f9cddc11536d7/lib/i18n/tasks/scanners/ruby_key_literals.rb#L23

**Comment by nbdavies** [comment]
Spaces in the key name also prevent i18n-tasks from detecting it: https://github.com/glebm/i18n-tasks/issues/359

Maybe the same solution would apply?

**Comment by ryanb** [comment]
@nbdavies I haven't had time to research when/where a space is allowed in a key, but I made a PR for a forward slash: #396. Feel free to do something similar for a space character if you need it.
