### ISSUE TITLE
Health task fails only in CI

### ISSUE THREAD

**Issue by afdev82** [glebm/i18n-tasks#387]
Hi all,
I have a very strange issue.
If I run in the GitLab CI the `health` task, it fails:

```
$ RAILS_ENV=test bundle exec i18n-tasks health
Forest (en, de) has 3963 keys across 2 locales. On average, values are 35 characters long, keys have 3.0 segments, a locale has 1981 keys.
✓ Good job! No translations are missing.
✓ Perfect! Every translation is in use.
✓ Good job! No inconsistent interpolations found.
The following data requires normalization:
Run `i18n-tasks normalize` to fix
config/locales/configurations.en.yml
config/locales/configurations.de.yml
```

But locally on the same commit it's OK

```
$ RAILS_ENV=test bundle exec i18n-tasks health
Forest (en, de) has 3963 keys across 2 locales. On average, values are 35 characters long, keys have 3.0 segments, a locale has 1981 keys.
✓ Well done! No translations are missing.
✓ Well done! Every translation is in use.
✓ Perfect! No inconsistent interpolations found.
✓ Good job! All data is normalized
```

Any idea how to fix that?
Thank you for your support.

**Comment by glebm** [comment]
Ensure that Ruby and libyaml versions are the same on CI and locally.

**Comment by afdev82** [comment]
Hi,

I checked the ruby version and it's the same:

```
$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
```

Regarding `libyaml`, do you mean [this library](https://github.com/yaml/libyaml)? How could I check its version?

**Comment by afdev82** [comment]
I've run  locally:

```
$ dpkg -l | grep libyaml
ii  libyaml-0-2:amd64                             0.1.7-2ubuntu3                                   amd64        Fast YAML 1.1 parser and emitter library
ii  libyaml-libyaml-perl                          0.69+repack-1                                    amd64        Perl interface to libyaml, a YAML implementation
```

and on CI:

```
$ dpkg -l | grep libyaml
ii  libyaml-0-2:amd64                  0.2.1-1                      amd64        Fast YAML 1.1 parser and emitter library
ii  libyaml-dev:amd64                  0.2.1-1                      amd64        Fast YAML 1.1 parser and emitter library (development)
```

**Comment by afdev82** [comment]
I don't know why, but the issue is not there anymore... I will close this issue.

**Comment by dsimardmtm** [comment]
I had the same error. Everything was OK locally and some files were flagged by `i18n-tasks check-normalized` on the CI server. In my case, it's Bitbucket Pipelines.

The `libyaml` version (see above: `dpkg -l | grep libyaml`) are the same. Ruby versions also the same.

The difference are in the empty translations. See

![image](https://user-images.githubusercontent.com/96206840/165093223-d5978e17-49e8-4a2f-8bc0-cab3de83eace.png)

One YAML file has a trailing whitespaces for empty translations.

I still don't know what is causing that.

**Comment by dsimardmtm** [comment]
I fixed the problem by removing all empty translations. Example, if I had:

````yaml
en:
  success: Success
  not_sure:
  failure: Failure
````

I changed it to:

````yaml
en:
  success: Success
  failure: Failure
````

Also, empty array items can be problematic. So this:

````yaml
en:
  months:
    -
    - january
    - february
    # All the other months
````
became : 

````yaml
en:
  months:
    - empty
    - january
    - february
    # All the other months
````
I still didn't find the root cause of this problem.

**Comment by davidwessman** [comment]
@dsimardmtm 
We fixed this issue in our team by everyong using libyaml 0.2.5, which is accessible on Mac OS but had to be compiled manually on Debian-based Linux versions. So that is probably why CI works differently.

Check which version you are using by running in `rails console`:

```ruby
[1] pry(main)> YAML
=> Psych
[2] pry(main)> YAML.libyaml_version
=> [0, 2, 5]
