### ISSUE TITLE
Does not work when `errors.add`.

### ISSUE THREAD

**Issue by yubele** [glebm/i18n-tasks#393]
I have added the following to my model, but ` i18n-tasks add-missing` and ` i18n-tasks remove-unused` did not work for this description.

```
errors.add(:text, :You_cannot_use_the_pass_through_syntax)
```

If you have a solution, please let me know. If not, we will consider PR.

**Comment by ryanb** [comment]
@yubele you can add `i18n-tasks-use` in comment where you have dynamic key generation.

```
# i18n-tasks-use t('errors.messages.foo')
errors.add(:text, :foo)
```

This way i18n-tasks will recognize it. This can be done other dynamic key generation such as label fields.

**Comment by yubele** [comment]
@ryanb Thanks for your information.
