### ISSUE TITLE
Bump version rubygems for Rails 7 support

### ISSUE THREAD

**Issue by navidemad** [glebm/i18n-tasks#406]
Hello,

Thanks again for your awesome gem.

Could you push the new version with the commit : [Fix compatibility with ActiveSupport 7+](https://github.com/glebm/i18n-tasks/commit/4799bb00e50d3712d1b9fb9c60999f3c80a3ff3a) into rubygems.

Otherwise we have to reference the github main in our Gem if we are running with Rails 7.0.0

**Comment by glebm** [comment]
v0.9.36 released
