### ISSUE TITLE
Aliases failing in missing_keys

### ISSUE THREAD

**Issue by colinbruce** [glebm/i18n-tasks#412]
Since updating to Ruby 3.1 we are running into an issue with Psych not allowing aliases by default https://bugs.ruby-lang.org/issues/17866

This manifests as 
```
I18n::Tasks::CommandError:
  yaml parse error: Unknown alias: applicant_error (file: config/locales/en/activemodel.yml)
```

Changing https://github.com/glebm/i18n-tasks/blob/main/lib/i18n/tasks/data/adapter/yaml_adapter.rb#L12 to
```ruby
YAML.safe_load(str, **(options || {}), aliases: true)
```
Allows us to load and run I18n-tasks.

I'm trying to add a test but I'm struggling with creating fake data that will test this behaviour

Can anyone provide any guidance on where to be creating this?

**Comment by glebm** [comment]
Alternatively, we have an existing file with the data layer tests here:

https://github.com/glebm/i18n-tasks/blob/933ce62ee99fdd041d0ecaec0c3784f315f328c6/spec/file_system_data_spec.rb#L65

**Comment by colinbruce** [comment]
I have split the PR into two, implement Ruby 3.1 and a separate test and fix for the Psych update issue.
Would you rather have a single PR with both?
