### ISSUE TITLE
DeepL translates variable names

### ISSUE THREAD

**Issue by dssjoblom** [glebm/i18n-tasks#417]
When using the DeepL API via i18n-tasks, variable names sometimes end up translated as well. From looking at the code, there seems to be an attempt to avoid this, but it doesn't work reliably. As a rough estimate, ca. 10% of variables end up translated. It also seems to be the same variables regardless of output language, as I've tried this with English to both French and German now, with the same result.

**Comment by glebm** [comment]
One option would be to treat even text translations as XML.

We'd need to HTML-escape them before sending to DeepL.

With XML translations, DeepL supports this natively.

**Comment by davidwessman** [comment]
@dssjoblom Can you add any example where the variable names get translated?

**Comment by dssjoblom** [comment]
@davidwessman yes, sorry for the late reply on this. You can try:

```
en:
  category: "%{model} or similar"
```
and `i18n-tasks translate-missing --backend=deepl --from=en es`.

It should yield:

```
es:
  category: "%{modelo} o similar"
```

**Comment by holstvoogd** [comment]
Just ran into this myself, fairly certain always setting tag_handling: 'xml' fixes it.
I'll do more testing tomorrow and make a PR if it turns out good

**Comment by SaraRavasio** [comment]
hello! is there an update here? we're also experiencing the same issue of variable names being translated 👀

**Comment by davidwessman** [comment]
I tried to fix it, but not sure what the effects are on all the translations, please try it out if you are able to:
https://github.com/glebm/i18n-tasks/pull/523
