### ISSUE TITLE
a way to mark "Inconsistent interpolations" as ignored?

### ISSUE THREAD

**Issue by timdiggins** [glebm/i18n-tasks#418]
We're using `i18n-tasks health` as a check, but some inconsistent interpolations are actually ok, e.g.

because in italian, the translation is

      posts_count:
        one: Ha commentato una volta
        other: Ha commentato %{count} volte

as opposed to in english

```
posts_count:
        one: Posted %{count} time
        other: Posted %{count} times
```

etc.

We could change the usage in `one:` to not use count in each language, or we could make sure that %{count} is used in each language, but actually it would be nicer to just let the translators do their thing, and then ignore the inconsistent interpolations - either with a specific comment in the yaml file, or a ignore marker (like https://github.com/glebm/i18n-tasks/blob/881ed6f3d2aed94fa0aae050584f9cddc11536d7/spec/fixtures/config/i18n-tasks.yml.erb#L44) in the config.

@glebm you'll recognise the use case I think 😉

**Comment by glebm** [comment]
i18n-tasks does support ignoring this but it's not documented!

https://github.com/glebm/i18n-tasks/blob/d7ae6e6e9158ae7581c1e36079eb32117d4aa77f/lib/i18n/tasks/interpolations.rb#L13

**Comment by timdiggins** [comment]
Thanks!
