### ISSUE TITLE
Automatic formatting

### ISSUE THREAD

**Issue by davidwessman** [glebm/i18n-tasks#428]
Hello 🙂 

I was thinking that it would be great to add some automatic formatting, rubocop is not enforced or used to format right now.

There are a few alternatives, I think we should add a commit-hook to automatically run on staged changes and:

1. Use rubocop for formatting.
1. Use [standardrb](https://github.com/testdouble/standard).
1. Use [prettier/plugin-ruby](https://github.com/prettier/plugin-ruby).

In my opinion:

1. Need to regularly update `.rubocop.yml` when new cops are added.

2. Opinionated but more seamless to update.

3. Requires javascript, so this project might not be a good candidate.

What do you think? Then we can either format all the files at ones, or do them each time it is edited.

**Comment by glebm** [comment]
We already do have .rubocop.yml, it is not yet enforced though.

The simplest would perhaps be to add a GitHub Workflow similar to this Travis CI job
https://github.com/thredded/thredded/blob/dd39074a8c2ea2bd406f14159c6756e0d7687c52/.travis.yml#L16-L26
