### ISSUE TITLE
Conflict with ActionText

### ISSUE THREAD

**Issue by alec-c4** [glebm/i18n-tasks#460]
Hey!
Strange behavior of your gem after adding ActionText to the project - i see following error

```
i18n-tasks: Error scanning app/assets/builds/application.js: Cannot resolve relative key ".concat(attachmentSelector, ".
Set search.relative_roots in config/i18n-tasks.yml (currently ["app/controllers", "app/helpers", "app/mailers", "app/presenters", "app/views"])
```

How can i fix it?

**Comment by alec-c4** [comment]
Yep, i did and error is gone. Should we add this line to config by default?

**Comment by davidwessman** [comment]
https://github.com/glebm/i18n-tasks/blob/main/templates/config/i18n-tasks.yml#L76
You can make a PR with the suggestion, then we'll see what the maintainer says 🙂

**Comment by glebm** [comment]
Yeah I don't mind adding it by default
