### ISSUE TITLE
Feature: Translate a group of messages instead of all of them

### ISSUE THREAD

**Issue by sylvieed** [glebm/i18n-tasks#468]
Currently, `translate-missing` can only translate _all_ of the missing messages in your locales at once. When translating a lot of messages (like when adding a new language), I prefer to go through them in groups.

I've implemented this locally by adding a `-p` pattern option to the `translate-missing`, `add-missing`, and `missing` commands. Are you open to a PR?

**Comment by glebm** [comment]
Sure, thanks :+1:
