### ISSUE TITLE
Normalization might fail if there are lists with empty items

### ISSUE THREAD

**Issue by raivil** [glebm/i18n-tasks#475]
Hey,
Not sure if this is a bug but I've experienced an issue with normalization failing when running specs on CI and wanted to share it here.
New values such as below were added to `en` and `pt` translations.
```
day_names:
    - 
    - Sunday
    - Monday
```

Note the empty list item (present on both languages).

That empty/blank item was added by mistake, and on development side I18n passed all the health/normalization checks. On CI it was failing the rspec `"files are normalized"` check. 
This was a weird failure, not consistent thought environments, and after removing the invalid blank value it worked as expected.

Best,

**Comment by glebm** [comment]
If the results on CI are different from the local results, it is usually because libyaml is a different version.

**Comment by davidwessman** [comment]
@raivil you can check these instructions:
https://github.com/glebm/i18n-tasks/issues/355#issuecomment-717846572
