### ISSUE TITLE
Not scanning t('string') if added into array

### ISSUE THREAD

**Issue by leoplct** [glebm/i18n-tasks#490]
I add the string into an array of string, but the **i18n-tasks unused** marks it as "unused". It pass if it's moved outside of array.
```
<% 
    warnings = []
%>

<% warnings << t("item_groups.alerts.out_of_budget") %>

<% if warnings.size > 0%>
    <ul class="ul-danger">
          <% warnings.each do |msg| %>
          <li><%=msg%></li>
          <% end %>
      </ul>
<% end %>
```

instead this works

```
<%  msg = t("item_groups.alerts.out_of_budget") 

    <% warnings.push(msg) %>
```

**Comment by davidwessman** [comment]
I tried to write a test case for this, and the only syntax I found not to work correctly was without parentheses:

```html
<% warnings << t 'this_key' %>
```

would get marked as unused. Can you include your version of the gem and a copy of your config file?

**Comment by davidwessman** [comment]
I'll close this until we get some more information to reproduce it.
