### ISSUE TITLE
grep_keys throws an ArgumentError with Ruby 3

### ISSUE THREAD

**Issue by helenasw** [glebm/i18n-tasks#491]
On version 1.0.12 with ruby 3.0.5, when I do:

```rb
I18n::Tasks::BaseTask.new.tree('en').grep_keys(/hello/)
```

I get an error like this:
```
/Users/helena.wentworth/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/i18n-tasks-1.0.12/lib/i18n/tasks/data/tree/traversal.rb:123:in `select_keys': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /Users/helena.wentworth/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/i18n-tasks-1.0.12/lib/i18n/tasks/data/tree/traversal.rb:164:in `grep_keys'
	from (irb):9:in `<main>'
	from /Users/helena.wentworth/.asdf/installs/ruby/3.0.5/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from /Users/helena.wentworth/.asdf/installs/ruby/3.0.5/bin/irb:23:in `load'
	from /Users/helena.wentworth/.asdf/installs/ruby/3.0.5/bin/irb:23:in `<main>'
```

I think it can be fixed by changing [this line](https://github.com/glebm/i18n-tasks/blob/497454f16141c87c1664392050c143e74a25c51e/lib/i18n/tasks/data/tree/traversal.rb#L164):
```rb
select_keys(opts) do |full_key, _node|
```
to this:
```rb
select_keys(**opts) do |full_key, _node|
```
because `opts` is a hash, but `select_keys` takes [keyword args](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

**Comment by davidwessman** [comment]
Could you try writing a test for it and add a PR?

**Comment by helenasw** [comment]
@davidwessman I'd be happy to! Do you have a suggestion for where to add the test?

**Comment by davidwessman** [comment]
Hm, maybe in `spec/locale_tree`, but I am not sure if we have some spec-setup you can copy.
