### ISSUE TITLE
Missing arguments are not reported in health check 

### ISSUE THREAD

**Issue by joshio1** [glebm/i18n-tasks#528]
First things - Love this gem and it helps a great deal to work with i18n files.

I have an `en.yml` which has this key: `text_your_student: text your student at %{phone_number}` and an `es.yml` file which has this key `text_your_student: envía un mensaje de texto a tu estudiante al %{phone_number}`.

When using this key in an html.erb file like this: `t('text_your_student')`, if I miss passing the `phone_number` argument, health check doesn't report this. Specifically inconsistent interpolations passes even though this `phone_number` argument is missing.

Is inconsistent interpolation only for checking if arguments are consistent between `en.yml` and `es.yml file`? Is there a way I can get the health check to fail if I miss an argument by mistake? (I did a brief check in the issues and pull requests and could not find anything related to this)

**Comment by davidwessman** [comment]
@joshio1 Sorry for a late answer, but the `health` command only checks that interpolation is consistent between locales, it does not check that parameters are correctly passed.
