### ISSUE TITLE
JRuby support?

### ISSUE THREAD

**Issue by megatux** [glebm/i18n-tasks#530]
The gem fails to install on JRuby, when installing better_html gem dependency (native c extension).

Env:
```
ruby -v
jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 21+35-2513 on 21+35-2513 +jit [arm64-darwin]
```

**Comment by megatux** [comment]
Could this gem be a dependency for MRI and not for JRuby (and TruffleRuby maybe)

**Comment by davidwessman** [comment]
Yes, we need to handle which matcher to use for ERB. But we could probably make it optional. Feel free to give it a try 🙂

**Comment by glebm** [comment]
It's entirely static analysis, so you can also just run it using MRI, even if your app uses JRuby.

**Comment by davidwessman** [comment]
@megatux on main there is a version without better_html now. Can you see if that works on jruby for you?

**Comment by megatux** [comment]
Seems to work fine. Thanks

**Comment by glebm** [comment]
I'll push a release after a week or two have passed, to let potential bugs get discovered.

**Comment by megatux** [comment]
Hi! was released yet?

**Comment by glebm** [comment]
v1.0.14 is now out! Release was somewhat delayed due to another unrelated bug.

**Comment by glebm** [comment]
We may want to consider adding jruby to the test suite to prevent regressions.

**Comment by glebm** [comment]
JRuby added to the test suite in https://github.com/glebm/i18n-tasks/commit/2a9a9e0d4803b30b7c1353d4d63357aaa251302d
