### ISSUE TITLE
What about those three dashes "---"?

### ISSUE THREAD

**Issue by jmuheim** [glebm/i18n-tasks#54]
When running `i18n-tasks add-missing`, there are always three dashes `---` at the top of the generated code:

![image](https://cloud.githubusercontent.com/assets/1814983/2693237/3447f08e-c3b1-11e3-99e5-17e9420a269e.png)

Googling for them, they seem to indicate a new Yaml file. But is this necessary? I've never seen them before.

**Comment by PascalPixel** [comment]
We are using Crowdin for managing our translations, and the outputs do not contain these dashes, hence i18n-tasks will fail the normalization check. Is there a possibility of adding a disable for this to the configuration options?
