### ISSUE TITLE
Upgraded Ruby version and unused_keys warns of wrong number of arguments

### ISSUE THREAD

**Issue by arinchoi03** [glebm/i18n-tasks#547]
Our tests were passing fine, but then I upgraded our ruby version from 3.0.5 to 3.1.4 and now our i18n_spec is failing with below:

```
     I18n::Tasks::CommandError:
       yaml parse error: wrong number of arguments (given 2, expected 1) (file: <insert filename>)
       ./spec/i18n/i18n_spec.rb:17:in `block (2 levels) in <top (required)>'
       ./spec/i18n/i18n_spec.rb:39:in `block (2 levels) in <top (required)>'
       ./spec/support/locale.rb:4:in `block (2 levels) in <main>'
------------------
--- Caused by: ---
ArgumentError:
  wrong number of arguments (given 2, expected 1)
  ./config/i18n_tasks_classes.rb:32:in `parse'

```

The error raises when establishing the variable in this way in our specs:
```
  let(:i18n) { I18n::Tasks::BaseTask.new }
  let(:unused_keys) { i18n.unused_keys }
```
...so it's not really calling this method with any arguments. How do I fix this?
 
code from our installed gem where the `unused_keys` is called (v 1.0.13): 
```
module I18n
  module Tasks
    module UnusedKeys
      def unused_keys(locales: nil, strict: nil)
        locales = Array(locales).presence || self.locales
        locales.map { |locale| unused_tree(locale: locale, strict: strict) }.compact.reduce(:merge!)
      end
```

---
I also tried running `bundle exec i18n-tasks unused` from my terminal and seeing the same error:
`i18n-tasks: yaml parse error: wrong number of arguments (given 2, expected 1) (file: config/locales/application_submitted/en.yml)`

**Comment by glebm** [comment]
What's in `./config/i18n_tasks_classes.rb:32`?

**Comment by arinchoi03** [comment]
oops, good question: `YAML.safe_load(str, options || {}, aliases: true)`
```
    def parse(str, options)
      YAML.safe_load(str, options || {}, aliases: true)
    end
```

**Comment by arinchoi03** [comment]
Looks like this is an issue with the `YAML.safe_load` method changing -- not an issue from i18n-tasks gem:

https://github.com/ruby/psych/discussions/571
https://www.ctrl.blog/entry/ruby-psych4.html
