### ISSUE TITLE
No detecting use of locale keys on form helpers

### ISSUE THREAD

**Issue by fguillen** [glebm/i18n-tasks#554]
The use of the locale key `activerecord.attributes.user.password`  is not detected even if it is used in a form helper like:

```
<%= f.label :password %>
```

Is this expected? is it a limitation of the library? or is a bug or something I am doing wrong?

**Comment by davidwessman** [comment]
There are no matchers for this case unfortunately. You can take inspiration from the different matchers we have added for model attributes and email subjects.

**Comment by fguillen** [comment]
Hi @davidwessman thanks for checking it out. I assume you mean [this example matcher](https://github.com/glebm/i18n-tasks/blob/main/lib/i18n/tasks/scanners/ast_matchers/rails_model_matcher.rb). 

I confess it looks like it would be a nightmare to try to infer what model is being used in a `f.label` tag. I assume we should have to parse all `.erb` looking for the proper model for the form. Not talking when the `f.label` is in a partial not including the parent `form`. 

Do you have any idea if this can be achievable for the task `i18n-tasks missing`?

**Comment by davidwessman** [comment]
Yeah, or add some magic comment for the form-model or something like that.

**Comment by davidwessman** [comment]
Since this is not a bug, but a known limitation I will close this for now.

**Comment by glebm** [comment]
Yeah, as it can be difficult even for a human to infer the right key name, magic comments or even simply calling `t` explicitly is probably the best solution here.
