### ISSUE TITLE
Version 1.0.14 thinks any method ending in `_t` is a translation method

### ISSUE THREAD

**Issue by mvz** [glebm/i18n-tasks#572]
I have a method `theme_t` that takes a string and is used in my ERB files. With version 1.0.14, i18n-tasks has started complaining that these string arguments cannot be found in the translation files.

It seems the relevant change is e939d0e1f51baaa5d8f229f54bc18d3cc438d71b, since the changed regex matches `theme_t "foo"` but the original regex did not.

**Comment by davidwessman** [comment]
Will check it out.

**Comment by davidwessman** [comment]
@mvz Could you add your `config/i18n-tasks.yml`?

**Comment by mvz** [comment]
@davidwessman thanks for taking care of this. I missed your request but it seems it's not needed anymore.

**Comment by davidwessman** [comment]
> @davidwessman thanks for taking care of this. I missed your request but it seems it's not needed anymore.

I figured it out, that it was not in an `.html.erb` but some other `.erb` 🙂
