### ISSUE TITLE
Normalize overruns line_width

### ISSUE THREAD

**Issue by jaredmoody** [glebm/i18n-tasks#578]
I'm seeing the normalize task consistently write lines that are longer than the configured `line_width` by including one more word than it should.

For example, given a `line_width` of 50, this file:

```
en:
  more_than_limit: >-
    On one line this is 53 characters
```

Incorrectly gets normalized to this:

```
---
en:
  more_than_limit: On one line this is 53 characters
```

**Comment by davidwessman** [comment]
There is not a lot of documentation on this option in Ruby, but this is what the YAML-library does.
https://docs.ruby-lang.org/en/master/Psych.html

Tests below are on Ruby 3.3.1.

For more weird behaviour with multiline and wrapping you can check out this PR and issue:
https://github.com/glebm/i18n-tasks/pull/568/files
https://github.com/glebm/i18n-tasks/issues/383

------

```ruby
require 'yaml'

as_string = <<~YAML
---
en:
  more_than_limit: >-
    On one line this is 53 characters
  more_than_limi2: >-
    characters line this one is on 53
YAML

width = 48
parsed = YAML.safe_load(as_string)

puts "Parsed and then dumped, line_width #{width}"
puts YAML.dump(parsed, {line_width: width})
```

```sh
% ruby spec/test.ruby
Parsed and then dumped, line_width 48
---
en:
  more_than_limit: On one line this is 53 characters
  more_than_limi2: characters line this one is on
    53
```

```sh
% ruby spec/test.ruby
Parsed and then dumped, line_width 50
---
en:
  more_than_limit: On one line this is 53 characters
  more_than_limi2: characters line this one is on 53
```

If this is not the behaviour you expect you would have to open up issues on ruby itself.
