### ISSUE TITLE
Unreadable output

### ISSUE THREAD

**Issue by ThibautGrx** [glebm/i18n-tasks#587]
I'm using i18n-tasks 1.0.14,  any command produce unreadable outputs : 

![image](https://github.com/glebm/i18n-tasks/assets/35230028/d3983704-d063-44bd-93e5-df1c6f8daf85)

Is anyone experiencing the same issue?

**Comment by Bilka2** [comment]
The table output of commands that show the value of translations can get pretty wide if the translations are long, and the dashes you see here are the bottom border of that table. Try redirecting the output into a file (e.g. `i18n-tasks unused > unused.txt`) and looking at that in a text editor with line wrapping turned off. Or you can change the output format with the `-f` option.

**Comment by davidwessman** [comment]
I'll close this, the suggestion from Bilka2 is a good one 🙂
