### ISSUE TITLE
Issue with single and double quoted strings in YAML locales

### ISSUE THREAD

**Issue by mscdit** [glebm/i18n-tasks#593]
Hi everyone,

I have a question. I’d like to introduce Crowdin to manage YAML locale files in a Rails app. However, I'm currently facing an issue: whenever Crowdin updates a locale file, it creates a merge request in GitLab where the string values in the YAML files are wrapped in double quotes. This causes the CI/CD pipeline to fail during the "i18n-tasks health" check.

Is there a way to adjust the gem so that it accepts the double quotes in the updated YAML files?

Best regards,
mscdit

**Comment by davidwessman** [comment]
I am not sure how the Crowdin integration works, but could you make it run i18n-tasks normalize on that PR as well? Maybe as a separate commit?

**Comment by davidwessman** [comment]
@mscdit Please get back to us if the suggestion did not help or you have more information to help us understand the situation 🙂
