### ISSUE TITLE
Haml extractor plugin! Sweet!

### ISSUE THREAD

**Issue by shaiguitar** [glebm/i18n-tasks#72]
Just ran across this repo. I made some i18n helper gem a while back that aids with automation of text extraction in haml. 

https://github.com/shaiguitar/haml-i18n-extractor 

Maybe it could be integrated as a task in this project.

Very nice gem!

**Comment by glebm** [comment]
There is also https://github.com/phrase/slimkeyfy, that extracts plain Strings from .slim views and Rails controllers.

**Comment by glebm** [comment]
I have mentioned all of the gems that I could find that handle key extraction in the wiki. If you write custom tasks for these, feel free to add them to the wiki.
